### ISSUE TITLE
portainer problem

### ISSUE THREAD

**Issue by J0hnnyb0y86** [LuatixHQ/opencti#1600]
portainer problem, i haved deploy the vm of opencti but i cant change env variables, on portainer i cant see it anyone have same problem?
![portainer](https://user-images.githubusercontent.com/23125390/135057445-09167dcd-06d2-4a2d-90f1-7c8e1da4f54a.png)

## Environment

1.Vm
2. OpenCTI version:5.0.0 { e.g. OpenCTI 1.0.2 }

**Comment by nor3th** [comment]
Hello @J0hnnyb0y86 

Please use the GitHub issue template for your question and verify that your question can't be answered by looking up already existing issues or doing a google search. By doing so you are helping us to invest the little time we have into improving OpenCTI instead of having to answer already solved questions again.

Feel free to ask your question in the slack channel without the question template, where there are more community members helping out with answering setup questions.

Closing this issue for now until the format requirements for a GitHub question have been fulfilled.

Regards,
