### ISSUE TITLE
[Custom Ontology] Ability to add/edit parameters for objects such as Malware, Indicator, Intrusion Set

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1602]
## Use case

To better describe objects in CTI

## Current Workaround

Leverage the Description to more accurately describe an object.

## Proposed Solution

Allow users/admins to add values to the following object/properties:

- Indicator
  - Indicator types
- Threat Actor 
  - Threat Actor types
  - Sophistication
  - Resource level
  - Motivations
- Intrusion Set
  - Resource level
  - Motivations
- Malware
  - Malware types
  - Architecture execution env
  - Capabilities
- Tool
  - Tool version (unclear if it's possible to edit this field in version 5.0.0)
  - Tool types (unclear if it's possible to edit this field in version 5.0.0)

## If the feature request is approved, would you be willing to submit a PR?

No, not a developer :(

**Comment by SamuelHassine** [comment]
Linked to #1244.

**Comment by SamuelHassine** [comment]
From Manon:

## Use case
It would be useful to deal with some attributes differently than it is done today: 
- for Threat actors and Intrusion sets --> goals, resource levels, motivations (primary, secondary)
- for campaign and incident --> objectives
- for malware --> malware type, operating_system_refs, architecture_execution
_envs, implementation_languages, capabilities 

For all these attributes, in most cases, lists are implemented, or in some cases it is a free field. When lists are implemented, they are from the list set up by stix and cannot be changed from the UI.

Two things would be desirable:
- for the fields which are free today (string expected), it would be useful to have lists instead. However, this is different from what is written in STIX so it might be impossible if we do not want to diverge.
- the lists should be manageable from the UI, just as it is possible to do so for type of reports today: in the parameters, in the lables and attributes tab, there could also be a menu to manage these attributes lists. By default, the list which are implemented today and given by STIX could be implemented, but could be changed. Or they could be a dataset as well.

## Current Workaround

No use of these fields because the information is not adequate.

**Comment by SamuelHassine** [comment]
From securitiz:

## Problem to Solve

Currently, TA types and motivations may not fit the taxonomy model of an org. The ability to add custom options, or edit/remove options, would be helpful.

## Current Workaround

Use the existing TA types, motivations. 

## Proposed Solution

Add the ability for admins to make changes to parameters available to users to describe TAs, such as the available TA types, motivations, etc.

## Additional Information

**Comment by SamuelHassine** [comment]
Synthesis:

* Put all current open vocabularies in the db
* Be able to customize entries in the settings
* **Be able to lock some open vocab entries** which are used as "built-in" types in the platform.
