### ISSUE TITLE
Create "is a sample of" relationship, for File -> Malware

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1805]
## Use case

This will help specify the relationship between a file and a Malware type. If there is a more proper way to clarity this relationship that I'm missing, please let me know :)

## Current Workaround

Use "relates-to" relationship type, specify nature of relationship in Description. However, having its own relationship type would be helpful, especially when filtering on relationship type in investigations

## Proposed Solution

Create "is a sample of" relationship for File -> Malware

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nor3th** [comment]
Hey @securitiz 

The `sample_refs` relationship between malware and file/artifact (https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_gc4ooz6oaz7y) is part of this PR for the next release. :smiley: #1803 

Regards

**Comment by securitiz** [comment]
yesss thank you for your work on this @nor3th !!!

**Comment by securitiz** [comment]
@nor3th are the following file-related relationships implemented in this release?

File -> sample of -> Tool 
File -> uses -> Attack Pattern
File -> located in -> Directory
File -> communicates with -> Domain, URL
TA / Intrusion Set -> uses -> File

No worries if not, happy to create a separate issue

**Comment by nor3th** [comment]
Hey @securitiz 

I wrote a parser for the STIX 2.1 documentation (https://docs.oasis-open.org/cti/stix/v2.1/stix-v2.1.html) and saved the resulting "normal' and nested relationships as a JSON file. Here's the one for the backend. https://github.com/OpenCTI-Platform/opencti/blob/86ac175a69c8925f4aba55460a9ea444bf2c4f62/opencti-platform/opencti-graphql/tests/data/stix_relationships-backend.json 
If you are able to find any relationship defined in the documentation, but not present in the JSON file, please let me know and I'll improve my parser. Here's the parser https://github.com/nor3th/furry-chainsaw/blob/main/opencti/relationships_test.py

Any relationship defined in the official STIX 2.1 documentation (+ a few custom opencti relationships) should be present in the JSON file and thus will be part of the PR. Also with the updated testing suite, OpenCTI should not have any untested implemented relationships anymore.

Some of your mentioned relationships are not present as described, but exist in some other way.

Regards

**Comment by securitiz** [comment]
Thanks for linking to the json, that's very helpful.

Based on the json, it seems like the relationship will be "malware -> _sample_ -> file". Is that right? If so, I feel like it makes more sense for it to go the other way, as in "file -> is a sample of -> malware". It's confusing because in the documentation, the relationship is a sample reference. What do you think?

**Comment by nor3th** [comment]
Hey @securitiz 

You have a valid point there. I think this issue might be the case for all non-adjective reference fields and to turn the direction of the relationship around.
- Process image_ref [File] -> relation: 
  - Process -`image`-> File
- Malware samples_ref [File, Artifact] -> relation; 
  - Malware -`sample`-> File/Artifact
- File opened_connection_refs [network-traffic] -> relation:
  - File -`opened_connection`-> Network-Traffic
...

This would require a custom function to convert those references from STIX to this turned relationship and back against when exporting to STIX. Could you help with that @SamuelHassine ?

Regards

**Comment by SamuelHassine** [comment]
@nor3th this is related to https://github.com/OpenCTI-Platform/client-python/issues/155 and https://github.com/OpenCTI-Platform/client-python/issues/241.

**Comment by SamuelHassine** [comment]
It will be implemented in 5.2.0.

**Comment by securitiz** [comment]
@nor3th I know this is late and the update is coming soon - I reviewed the JSON again and noticed "file" -> drops -> "file" isn't there, and isn't documented in STIX. It makes a lot of sense to me to include it, however - what do you think?

**Comment by nor3th** [comment]
Hey @securitiz 

Thanks for the idea. Since there is already a `malware` - drops -> `malware,tool,file` relationship I'd leave it to that for now. Also I'd like to limit the custom relationships to an absolute minimum, as the TI shareability decreases with too many custom relationships.

Which use case would require a `file` -drops-> `file` which wouldn't also be covered with the relationship mentioned above or the `tool` -drops-> `malware` relationship?

Regards

**Comment by securitiz** [comment]
I think it comes down to the difference between SDOs and SCOs, and perhaps this is an area where I can learn more about the STIX specifications

It makes sense that some Malware can drop another Malware SDO object. However, we want to capture when specific files (identified a hash) drop another file (identified by a different hash). Malware objects and their relationships don't allow us to do that.

The goal is for our malware analysts to be able to demonstrate that one file drops another file, and for other analysts to see that when they view either file. 

In the picture I've attached below - the existing Malware -> drops -> Malware relationship doesn't make clear that file 2 specifically drops file 7

![image](https://user-images.githubusercontent.com/78382789/158094622-4ce3812b-34bd-44ba-8170-bddf2dbae24b.png)

**Comment by nor3th** [comment]
Hey @securitiz 

Thanks for your explanation.
However since my focus for this PR was to properly implement the official STIX relationships, I'll leave this request out of the PR. However please open a feature request for a custom STIX relationship and we'll decide later on whether we'll implement this or not.

Regards

**Comment by SamuelHassine** [comment]
I'm re-opening this issue because we need to implement the `sample_refs` in the Malware entity on the frontend and backend sides. It will be quick but it's not fixed in 5.2.2.

**Comment by nor3th** [comment]
Hey @SamuelHassine 

I think malware's `sample_refs` is currently implemented. Here's how:
My approach was to convert all nested relationships into 'proper' ones. Hence I made out of `sample_refs` the relationship -Malware - `sample` -> File.
As @securitiz correctly pointed out above (https://github.com/OpenCTI-Platform/opencti/issues/1805#issuecomment-1013607061) the `relationship will be "malware -> _sample_ -> file". [...] If so, I feel like it makes more sense for it to go the other way, as in "file -> is a sample of -> malware"`

Due to this, I turned all non-verb relationship around (as defined here https://github.com/OpenCTI-Platform/opencti/pull/1803#issue-1097307977). This made the mentioned relationship look like this now: File - sample -> Malware (read as "File is `sample` of Malware").

Thus Malware's `sample_refs` nested relationship referencing to files and artifacts has become `File/Artifact - sample -> Malware` as defined here:
* frontend   
  - https://github.com/OpenCTI-Platform/opencti/blob/813fa07e2fb7844e8ad7c9465fefd6d5e024f5ef/opencti-platform/opencti-front/src/utils/Relation.js#L224
  - https://github.com/OpenCTI-Platform/opencti/blob/813fa07e2fb7844e8ad7c9465fefd6d5e024f5ef/opencti-platform/opencti-front/src/utils/Relation.js#L258
* backend
  - https://github.com/OpenCTI-Platform/opencti/blob/813fa07e2fb7844e8ad7c9465fefd6d5e024f5ef/opencti-platform/opencti-graphql/src/database/stix.js#L900
  -  https://github.com/OpenCTI-Platform/opencti/blob/813fa07e2fb7844e8ad7c9465fefd6d5e024f5ef/opencti-platform/opencti-graphql/src/database/stix.js#L894

For the STIX import/export the `sample_refs` as all the other nested relationships have to converted to/from the SROs of type `sample`.
