### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by namnori72** [LuatixHQ/opencti#1820]
## Environment

1. OS (where OpenCTI server runs):  Ubuntu 16.4,
2. OpenCTI version: OpenCTI 5.1.3

Hello, I updated OpenCTI from v4.5.5 to 5.1.3 but after this process I lost content of my db - the information I added earlier has disappeared and also there are no users.

**Comment by richard-julien** [comment]
Hi @namnori72 , im sorry but its almost impossible to help you with this kind of ticket.
Do you have any backup of your 4,5,5 database?
If yes, and your problem is reproductible, could be very interesting to share it with us.
If not coud be very difficult and completely specific to fix your database.

**Comment by namnori72** [comment]
Thank you @richard-julien for a quick reply.
I came back to 4.5.5 but it's my second attempt to do update - last time i tried to update to v5.1.1 or v5.1.2 nearly 1 or 2 month ago

**Comment by richard-julien** [comment]
Do you think its possible for you to share a backup of your elasticsearch database?

**Comment by namnori72** [comment]
Sorry, I can not.
I started use OpenCTI again, If I have a problem with the new update, I will post here again.

**Comment by richard-julien** [comment]
Ok. I close this ticket for now.  If this problem occurred again, please create a new issue. Thanks
