### ISSUE TITLE
Question on OpenCTI STIX ID implementation

### ISSUE THREAD

**Issue by jieyu-lin** [LuatixHQ/opencti#1844]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

I currently review some object Standard STIX ID on opencti console. I am just confused about why using <object-type>--<uuid5> as a stix domain object standard id. The screen shot is on opencti.io and I click an random report.
![截圖 2022-01-12 12 56 00](https://user-images.githubusercontent.com/51392682/149066453-bdd1d201-a565-43be-b009-0ef7cac60e72.png)

I know there is an info icon indicates that it is a predictable id, so it possibly using uuid5 as stix id. However, I look up in stix2.1 standard document and it says stix domain object SHOULD use <object-type>--<uuid4> as object id.
![截圖 2022-01-12 13 00 49](https://user-images.githubusercontent.com/51392682/149066748-6bef09e7-b609-4ff8-a458-54ce9cb6cb23.png)

It turns out when we use pycti api to export a standard stix2.1 objects, it used "Standard STIX ID" (<object-type>--<uuid5>) as its object id rather than using Other STIX ID (<object-type>--<uuid4>), which cause stix-validator error (id checking failed).

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version:  OpenCTI 5.1.1
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. just click any stix domain objects on opencti.io platform

## Expected Output

Expected a standard stix id SHOULD follow stix2.1 standard documents of <object-type>--<uuid4>

## Actual Output

Now standard STIX ID are <object-type>--<uuid5>

**Comment by nor3th** [comment]
@SamuelHassine @richard-julien Your thoughts on this?

**Comment by richard-julien** [comment]
Hi @jieyu-lin,

We decide to generate a uuidv5 as a standard id depending of data to have a powerful way of reconciliation for same elements coming from different sources that have different uuidv4. 

In my opinion we respect the specification because OpenCTI generate uuidv5 with its own namespace to prevent collision and so respect the guideline (see  if generating a UUIDv5 in the spec)

**"they MUST NOT use a namespace of 00abedb4-aa42-466c-9c01-fed23315a9b7 if generating a UUIDv5.."**

for info OPENCTI_NAMESPACE = 'b639ff3b-00eb-42ed-aa36-a8dd6f8fb4cf';

**Comment by nor3th** [comment]
Closing this since the question should have been sufficiently answered.
