### ISSUE TITLE
Relationship `resolves-to` for domain-name not possible

### ISSUE THREAD

**Issue by axelfahy** [LuatixHQ/opencti#1985]
## Description

In OpenCTI 5.2.2, it is not possible to create a relationship `resolves-to` between a domain-name and another domain-name or an ipv4-addr or an ipv6-addr. 

## Environment

1. OS (where OpenCTI server runs): docker
2. OpenCTI version: 5.2.2
3. OpenCTI client: both
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a domain-name
2. Create an ipv4
3. Try to create a relationship `resolves-to` between both of them.

## Expected Output

The relationship `resolves-to` is possible. 

## Actual Output

The only option is the `related-to` relationship.

## Additional information

<img width="881" alt="image" src="https://user-images.githubusercontent.com/7095119/159927097-93aadec7-8907-4998-bace-3570b01654cd.png">

**Comment by nor3th** [comment]
Hey @axelfahy 

Thanks for reporting this. Creating this relationship does work, but only via creating a `linked observable` instead of a `relation`

![img](https://user-images.githubusercontent.com/73965465/159990146-11792b79-8153-4e01-a681-803abbe78aa2.png)

Via linked observables this is possible

![image](https://user-images.githubusercontent.com/73965465/159991496-3455225b-4530-4a7b-8ed3-e6467b0fadaf.png)
https://demo.opencti.io/dashboard/observations/observables/eaa13b07-e94e-424a-beb4-0a859ce5b295/knowledge

@SamuelHassine Correct me if I'm wrong, but the difference between `linked observabes` and a `relation` is, that 1) references to nested relations (like for domain's `resolves_to_refs` nested relationship). 2) references to proper SROs as defined in STIX.

I don't know why the CTI TC chose this path, but I think for an analyst it shouldn't matter whether below the hood it is a nested relationship or an SRO. They want to build relationships. @SamuelHassine Would it be a feasible approach to implement in the future *only* relationships and in the backend we either go for the approach I chose here https://github.com/OpenCTI-Platform/opencti/issues/1805#issuecomment-1077625331 or via nested relationships in the graphql schema? Thoughts?

Regards

**Comment by SamuelHassine** [comment]
Hello @nor3th,

Linked observables = embedded "refs" relationsips
Relations = SRO

resolves-to is both SRO and embedded resolves_to_refs :)

**Comment by SamuelHassine** [comment]
![image](https://user-images.githubusercontent.com/1334279/160028336-6d9942fa-3325-461d-b6af-9545f3c7e9ac.png)

SRO `resolves-to` actually exits in the standard, along the `resolve_to_refs`.

**Comment by axelfahy** [comment]
Thank you for the reactivity!

**Comment by nor3th** [comment]
My bad, my the logic behind my STIX parsing script didn't take into account, that STIX 2.1 would have a SRO **AND** a nested reference for the god damn same thing... :see_no_evil:
