### ISSUE TITLE
Implement deduplication of Process objects

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1995]
## Use case

Duplicate process objects are confusing and unhelpful

## Current Workaround

manually find duplicate process objects, and delete duplicates, merge their relationships, etc

## Proposed Solution

Implement deduplication of process objects

## Additional Information

![image](https://user-images.githubusercontent.com/78382789/160185740-d5bd86bc-c760-4259-b0f9-d202ba28880a.png)

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment]
Hello @securitiz,

The de-duplication on process is done using the PID and the command line. Do you have example of duplicates with the same PID and the same command line?

As STIX 2.1 is not providing any guidance for de-duplication of these SCO, do you think we need to use `cwd` and `command line` instead of the PID?

Kind regards,
Samuel

**Comment by securitiz** [comment]
In our use case, we often don't have `cwd `and almost never have `PID`. Do you see a reason not to de-duplicate only on the `command line`? For example, I would want to know if `command line` showed up in multiple reports, regardless of the `cwd` and `PID`
