### ISSUE TITLE
Stream filter not working

### ISSUE THREAD

**Issue by Tonnulus** [LuatixHQ/opencti#2021]
## Description

I created a data stream (Data Sharing) with the following filters `Marking definition: TLP:WHITE OR TLP:GREEN AND Revoked: No AND `. But I found in the stream `marking-definition` and `identity` events

## Environment

OS debian
OpenCTI version: 5.2.3
OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Stream (Data Sharing) 
2. Add this filter `Entity type: Indicator`
3. Check the stream 

## Expected Output

Only Indicator

## Actual Output

A lot of Indicator but also some Marking-Definition and identity

**Comment by richard-julien** [comment]
Hi @Tonnulus, this behavior is expected by default because the live stream take care of resolving dependencies. If your indicator has a marking, a created-ref etc elements will be pushed in the stream to ensure consistency.
For now we propose an option "client side" as a query parameter /live?no-dependencies=true but nothing server side.

**Comment by Tonnulus** [comment]
Hi @richard-julien thank you very much for your response.

**Comment by SamuelHassine** [comment]
Hello @Tonnulus,

I will add the `no-dependencies` parameter in the Python library method `ListenStream` for the next release. 

Kind regards,
Sam

**Comment by SamuelHassine** [comment]
Please refer to: https://github.com/OpenCTI-Platform/client-python/commit/67f8062bda3cfaa346e7c1a49ffaa1e432f7eb9c.
