### ISSUE TITLE
Add day to Timeline date

### ISSUE THREAD

**Issue by YungBinary** [LuatixHQ/opencti#2183]
## Use case

We are looking for a solution where the `day` number is added to the timeline (Incidents/Analysis). Right now only the month and year are shown.

## Additional Information

Please see the following screenshot for more context, e.g. May 2022 instead of May 01 2022:

![image](https://i.imgur.com/89RDBiS.png)

**Comment by SamuelHassine** [comment]
Hello @YungBinary,

Please can you precise where is this timeline? Because in the latest versions, Incident Knowledge TimeLine has precise dates:

![image](https://user-images.githubusercontent.com/1334279/175377649-0cd8f4bf-c109-4fd3-8e4c-30ded0575c00.png)

https://demo.opencti.io/dashboard/events/incidents/8afc6e03-f3e2-42c6-9540-7b7b429c39fc/knowledge/overview

Kind regards,
Samuel

**Comment by YungBinary** [comment]
@SamuelHassine Thank you very much for the information! We will have to upgrade.
