### ISSUE TITLE
GrahlQL stixCoreRelationships toTypes and fromTypes using wrong syntax

### ISSUE THREAD

**Issue by Root-DE** [LuatixHQ/opencti#2191]
## Description

The stixCoreRelationships use filters (fromType, toType) where the entity types must contain spaces, such as "Attack Pattern" (unlike other filters).

## Environment

demo.opencti.io

## Reproducible Steps

Steps to create the smallest reproducible scenario:
run this graphql query:
```
query issue {
  stixCoreRelationships {
    edges {
      node {
        x_opencti_stix_ids
        to {
          __typename
          ... on AttackPattern {
            id
            name
          }
        }
      }
    }
  }
}
```
it outputs something like:
![image](https://user-images.githubusercontent.com/58123348/176964367-391c0101-f97d-4fa3-bbd7-d01b05f779bd.png)

but when using a filter, e.g.:
```
query issue {
  stixCoreRelationships(toTypes: ["AttackPattern"]) {
    edges {
      node {
        x_opencti_stix_ids
        to {
          __typename
          ... on AttackPattern {
            id
            name
          }
        }
      }
    }
  }
}
```
it outputs nothing, like you can see here:
![image](https://user-images.githubusercontent.com/58123348/176964274-5c3bbe1d-0563-4f92-b1b5-2ad98d2b031d.png)

For some examples the filters work.
## Workaround
If you use the entity names with spaces, such as "Attack Pattern", it works, but this is against the schema.
I would like to ask one more thing regarding the fix, please no breaking change, please continue to allow the old syntax with spaces.

**Comment by SamuelHassine** [comment]
Hello @Root-DE,

Thanks for this interesting question / finding. Actually, the stored entity type in our database is `Attack-Pattern`, `Intrusion-Set` (with a dash). The fact this is working with a space is just because ElasticSearch is successfully handling that correctly.

When using filters on entity types (whether it is on relationships query or even or raw StixDomainObject queries, you have to use the correct type) which are available starting this line: https://github.com/OpenCTI-Platform/opencti/blob/e2078dc6b74a1c4250301c9d50944e06c8e11091/opencti-platform/opencti-graphql/src/schema/stixDomainObject.ts#L27.

Kind regards,
Samuel
