### ISSUE TITLE
theHive integration can use the same DB

### ISSUE THREAD

**Issue by 0l4y4** [LuatixHQ/opencti#2192]
Hi,

I am a new openCTI user and I want to integrate it with my thehive and MISP. The question is, do I need another elasticsearch? or can I use the current for theHive?

Thanks!

**Comment by adel-akloul-mox** [comment]
As per [TheHive official documentation](https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/database/#use-cases), it uses Janusgraph to support the processing of large graphs by a cluster.
In every use cases, you need a Cassandra engine but the Index backend, instead of being local, can be an Elasticsearch Cluster - see [Janusgraph "Mixed Indexed Backend" documentation](https://docs.janusgraph.org/index-backend/elasticsearch/) -

Elasticsearch is only required if you want to manage TheHive index as a cluster, otherwise it does not make sense. 

Also it is more secure and simpler to maintain your ecosystem (e.g upgrade, backup, rollback ...) if you set some boundaries into your ecosystem such as separate your databases ... etc ...

**Comment by AliByte01** [comment]
> Hi,
> 
> I am a new openCTI user and I want to integrate it with my thehive and MISP. The question is, do I need another elasticsearch? or can I use the current for theHive?
> 
> Thanks!

you can use the existed one, all you have to do is to just connect from from the opencti connectors list

**Comment by SamuelHassine** [comment]
I confirm, you can definitely use an already existing ElasticSearch cluster to deploy OpenCTI.

Kind regards,
Samuel
