### ISSUE TITLE
Full refactor of filtering and searching using grouping / operators / fuzzy filters

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#2686]
## Use case

Adding the possibility to switch between the AND and the OR operators in filters

## Solution

When some filters are selected, clicking on the 'OR'/'AND' button between filters would switch to the AND/OR operation between those filters.

## Comment
Global filter refacto also done in this issue.

## Notion page
https://www.notion.so/filigran/Switch-AND-OR-operators-in-filters-change-filters-format-d05fe9af797c4751a293e3a7046ef89d#23a6b0fb69c94d2a8b837b50184c60b8

**Comment by ristowee** [comment]
This would be nice.
Currently there's no way to allow unmarked objects in the filter, e.g. "CLEAR **OR** GREEN **OR** unmarked". I tried to go around it by creating a negated filter forbidding AMBER, AMBER+STRICT and RED with a "**NOT**(AMBER **OR** AMBER+STRICT **OR** RED)" but that wasn't possible because in negated filter the combiner operator was **AND**.

**Comment by Archidoit** [comment]
Will also be resolved in this issue : https://github.com/OpenCTI-Platform/opencti/issues/4323 (Filters not working for Threat Actors Individual)
