### ISSUE TITLE
Searching for Indicator Pattern Value

### ISSUE THREAD

**Issue by annoyingapt** [LuatixHQ/opencti#2876]
## Description
Currently there is an issue when searching for a URL pattern in the search or via graphql.
Other types of indicators, ipv4-addr, domain-name, file:hashes.MD5 work fine.

## Environment

- OS (where OpenCTI server runs): Portainer stack
- OpenCTI version: OpenCTI 5.5.4

## Reproducible Steps

1) Add the following indicators into OpenCTI. (I defanged the IP and URL when posting to github as the IP was picked at random)
190.97.207[.]86
http://190.97.207[.]86/1.php
exampledomain.com
9c3fcf828968083831a97ef62d6b71a3

2) Search for the indicators, you will need to wrap the pattern in quotation marks
"[ipv4-addr:value = '190.97.207.86']"
"[url:value = 'http://190.97.207.86/1.php']"
"[domain-name:value = 'exampledomain.com']"
"[file:hashes.MD5 = '9c3fcf828968083831a97ef62d6b71a3']"

## Expected Output

All pattern searches should return the indicator you are searching for.

## Actual Output

[ipv4-addr:value = '190.97.207.86'] - works
[url:value = 'http://190.97.207.86/1.php'] - returns no results
[domain-name:value = 'exampledomain.com'] - works
[file:hashes.MD5 = '9c3fcf828968083831a97ef62d6b71a3'] - works

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/55898651/218612017-eedcd32b-7ef1-427e-bfbb-c6dea8a733b8.png)
![image](https://user-images.githubusercontent.com/55898651/218611949-97a73894-52ad-4a23-8e23-3cb043d38b5a.png)

**Comment by nino-filigran** [comment]
@annoyingapt I assume this issue has been resolved since then, since I've tried several approach and successfuly managed to find what I was looking for. Also the introduction of the filter "pattern" with the operator contains ease even more this search.

As a result, I'm closing this ticket. If you disagree, have a comment or a question, feel free to reopne this ticket. I'll be happy to answer it.
