### ISSUE TITLE
Full migration to a new server

### ISSUE THREAD

**Issue by Honkshu** [LuatixHQ/opencti#2904]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

Hi, is there an effective method to backup and restore the database to a new server? I need to migrate this application from one server to another and don't want to re-enter data manually. 

Looking through the documentation, I do see there is an import/export function. I've exported the data in my old instance to .json and to .csv. 

When I uploaded the .csv to the new instance, it stated that the upload had completed successfully, however no data was populated. 

As for the .json upload, it will not complete. I saw another github issue describing this same problem, and the response was to ensure there is at least 1 OpenCTI worker running. I have confirmed this. 

Is there a better way to accomplish what I need, which is an exact clone of my current instance? Is there a database file I can copy over? 

Thank you!

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 5.5.4

## Reproducible Steps

N/A

**Comment by CyberKaizen** [comment]
Are you using Docker?

**Comment by Honkshu** [comment]
I am, and when I tested the upload again today, it completed successfully. Not sure why, as nothing changed in my environment. 

I did have some trouble with some data not transferring over, some errors, as well as relationships with null values. Is this the most effective way to do a full backup/restore in the future?

**Comment by CyberKaizen** [comment]
One of the things I did was set up the Elasticsearch data on separate drive. So when I needed to switch systems or re-install the OS. I would simply attach that drive to the new system then modify my compose file with a new bind mount pointing to that data. Then when you start the OpenCTI service everything works.

But if you have not done that and are using the default docker compose file located here: https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml

Docker supports doing something like this migration, but requires you know some fundamentals about how Docker works:
https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes

On Ubuntu 20.04 LTS
You can:
1. Backup the esdata volume (by default it will be located in /var/lib/docker/volumes) on old system to a share (I recommend making two copies on two separate shares/drives if this is your first time as you can accidentally wipe out your data, better yet practice this procedure with a copy of OpenCTI stood up on your laptop or desktop)
2. After confirming the integrity of the copied data matches the old data
3. Mount share to the new system
4. After installing everything on your new system to run docker, you mount the share containing your esdata volume to new system.
5. Copy data to new system
6. Elasticsearch can have problems reading data if permissions are not set correctly. Switch into the top level directory containing your esdata volume folder and run "sudo chown 1000:0 <name of esdata volume folder here>"
7.  Update your compose file to bind mount the directory containing your esdata. Update the log level on your containers to debug so that you can check for errors or issues.

*If your Elasticsearch database is big you may need to compress the volume, copy to share, then copy and extract to new system.
