### ISSUE TITLE
Investigation graph exports are blank

### ISSUE THREAD

**Issue by mattreduce** [LuatixHQ/opencti#2937]
## Description

When exporting an investigation as a PDF or PNG image, I see the investigation title at the top but the graph is empty

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04 Linux
2. OpenCTI version: 5.5.2
3. OpenCTI client: Frontend
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Create an investigation
2. Add elements to the investigation
3. Click Export to PNG or PDF, choose either Light or Dark

## Expected Output

PDF export should look like the investigation graph with nodes and edges

## Actual Output

The PDF (or PNG image) is empty, except for the investigation title and the export icons (unrelated, but these icons are probably there by accident and should be excluded from the export)

## Additional information

N/A

**Comment by SamuelHassine** [comment]
Hello @mattreduce,

I'm not able to reproduce in master branch / demo env. This may be fixed by an upgrade of some libs but not sure.

Are you able to export investigation in demo? If no, can you please tell me which browser / version you're using and if you have any error in the console log?

Thanks!

Kind regards,
Samuel

**Comment by mattreduce** [comment]
I'm not sure what went wrong before (possibly browser config-related) but I don't have this problem anymore. Thanks, @SamuelHassine!
