### ISSUE TITLE
Connector unreliable works status

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#3313]
## Description

Please read this thread: https://filigran-community.slack.com/archives/CHZC2D38C/p1683545058684059
As soon as a connector send a bundle to opencti, in case opencti processes that bundle received before the connector sends the next bundle collected, the work will be considered as completed and the stats about the total operations will be unreliable. I also have a suspicious that we might be loosing data on this behaviour.

## Environment

OpenCTI version: 5.7.4

![image (1)](https://github.com/OpenCTI-Platform/opencti/assets/4184292/3b6f900a-f4f8-49ff-9df5-1eedfdc3c566)

**Comment by richard-julien** [comment]
After some digging about that, the problem here is more about the connectors that needs to be smarter in job generation to compute all bundles that need to be injected in only 1 pass.
Unfortunalty this situation needs to be handle in each connector that needs to be improved.
As i dont know the connector we use for this ticket, i will close it and ask you to create a ticket in the connector repository talking about this problem mentionning the connector we need to fix.
Thanks
