### ISSUE TITLE
Add Label as Entity in Investigations

### ISSUE THREAD

**Issue by markusneis** [LuatixHQ/opencti#3465]
## Use label as Entity Pivot point

During investigations labels allow to identify overlaps as well as relationships outside of the entity relationships (eg. when its not clear yet that a relationship exists)

## Current Workaround

None

## Proposed Solution

Add the labels as Entity to expand elements

## Additional Information

![image](https://github.com/OpenCTI-Platform/opencti/assets/103125122/3885073b-33cb-4d6d-a33e-74cc6ab8ee80)

## Label is further not showing any results 

![image](https://github.com/OpenCTI-Platform/opencti/assets/103125122/4d853100-1bea-4d89-83ce-6cc6efff0cf2)

**Comment by Jipegien** [comment]
You can already pivot from labels, by expanding an entity in the investigation graph. But you cannot filter this to expand only to labels. 
The label object's detail window is showing nothing because label has no attributes to show.

--> feature to develop : 
- filtering graph expansion with label
- having a details windows handling labels with something that is not an error message.

**Comment by Jipegien** [comment]
It is now covered in 6.0
