### ISSUE TITLE
Error at creation of a threat actor in a knowledge section

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3635]
## Description
- Go to a region overview (or another entity type overview).
- Go to the Knowledge tab.
- Click on 'Threat actors' on the right panel
- We see entities, even if there are not threat actors. -> first bug
- Click on the 'add' button
- an error occurs -> second bug

**Comment by SouadHadjiat** [comment]
I found other bugs on threat actors (reproduced on demo)
- It's not possible to update "threat actor types" on a threat actor indivudal. 
- Not reproduced yet, but I've created earlier today a threat actor individual, but it transformed itself later to a threat actor group : https://demo.opencti.io/dashboard/threats/threat_actors_group/1acf7b88-3124-4f76-bee2-eb4ec60f1e8f, can't find how in the entity history log.  => the migration was updated since, and the indivudal became group because resource level is unknown.
- When we create a threat actor individual, the resource level is always unknown, why ?
