### ISSUE TITLE
No updater when adding/removing entities in a graph

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#4221]
## Description

No updater when adding/removing an entity in a graph

## Reproducible Steps

- Go to a report knowledge graph (or an investigation graph, or an other entity knowledge graph)
- Add some entities
- Click in the graph to see the whole graph
- Open again the entities-adding panel
- The added entities are not checked
- If you reload the page (or go elsewhere and come back to the graph), and open the panel, the entities are right crossed.

(same bug for entities removing)

## Proposed solution
Use an 'updater' after the commit of adding/removing an entity in a graph.

## Screenshot

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/3dab919c-2a28-4de1-b8f2-49b6a5e3ebb1)

**Comment by RomuDeuxfois** [comment]
After investigation, we found :

**First point**
- Hierarchy
ContainerAddStixCoreObjects > ContainerAddStixCoreObjectsLines > ContainerAddStixCoreObjectsLine

- The list in the panel is handle by this component `ContainerAddStixCoreObjectsLine` where addedElements is given to know if we already have the object in the graph or not.

- An updater which update the addedElements with a state in the `ContainerAddStixCoreObjectsLines` component

- A query renderer to have objects to display in panel in the `ContainerAddStixCoreObjects` component

When we go out of the panel, components are destroy because there are wrapped by the Query Renderer

**Second point**
The addedElements is fetch and given by an upper component `ReportKnowledgeGraph`
The hierarchy is ReportKnowledgeGraph > ReportKnowledgeGraphBar > ContainerAddStixCoreObjects 

We don't need to fetch a data in component A used by a component C

What we suggest :
- Refactoring components and their hierarchy  to follow React concept (independent, atomic) when [refactoring](https://github.com/OpenCTI-Platform/opencti/issues/3524) the graph component
