### ISSUE TITLE
Separation of label management function and site setting function

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#4247]
In the case of our organization, there are many people who enter reports, so we have them create/delete labels individually.

However, when granting permission to create/delete labels, the site setting function is also forcibly granted, so when each user changes the settings (Theme, etc.), it is also forcibly applied to all other users.

Can you separate the permission to create/delete labels and the permission to set up the site?

![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/09643f48-ea08-49e8-84f1-69150c42b516)
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/0d35959b-16ac-4a1c-b553-d2434b6b7a55)

**Comment by nino-filigran** [comment]
@misohouse, this is indeed a problem, that we will tackle (not now however, since we have more urgent topics to handle now). We'll update the ticket when we'll work on it also to explain the chosen solution.

Right now we are thinking about the following solutions:
- reshape the RBAC capability for security to have basically a single capability per page (one for parameter, one for security...)
-    if user has only access to a capability, directly pormpt him this page when clicking on settings
- only add a capability to manage parameters
- add in user profile the capacity to manage language, theme and inherit from local settings too.

**Comment by nino-filigran** [comment]
Currently being developed, will be delivered in 6.2 https://github.com/OpenCTI-Platform/opencti/issues/5550
