### ISSUE TITLE
Icon resolvers are missing in IPv4 / IPv6 / StixFile

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4254]
## Description

1. Create a custom dashboard
2. Choose List (distribution with numbers)
3. Filter on Type Observable
4. Distribute on Type

https://filigran.octi.filigran.io/dashboard/workspaces/dashboards/6c25e9a7-19f0-4e4e-badd-33adaeefbdd9

Interrogation point instead of the observable icon:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/27cf0536-5822-4469-9448-1c8843c58cd2)

**Comment by RomuDeuxfois** [comment]
Problem found : 

We display the item icon from the label field.
The label field comes from stixCoreObjectsDistribution query.
This query is resolved, in our case, by this callstack : stixCoreObjectsDistributionByEntity > distributionEntities > elAggregationCount.
At line 1628, the key is pascalize and leads to Ipv4-Addr instead of IPv4-Addr.
