### ISSUE TITLE
[FR] - Add the ability to expand entities added to the Knowledge tab for Reports and Incident Response cases & add graph view to Incidents

### ISSUE THREAD

**Issue by CyberKaizen** [LuatixHQ/opencti#4327]
## Use case

**Part 1**
Currently expanding entities visible in graph view is only supported for the Investigations workspace.

It would be nice to be able to do this in order to tie other entities to a Incident Response or Report container.

For example, an alert comes in with information containing Org impacted and IOCs.

A forensics investigation is launched and the investigator creates a Incident Response container. They add the Incident to their Incident Response container but when they go to look in the Knowledge tab all they see is the one Incident entity. They wish to expand that entity to add some of the nested objects inside the one entity to their container.

**Part 2**
Creating relationships and objects in Events of the Incident type requires too many clicks and page switches.

Adding Graph View to allow creating relationships there would be a significant QOL improvement.

## Current Workaround

**Part 1**
Manually add entities to a container that might already be nested inside an entity. This causes duplicative work.

**Part 2**
If using Events of the Incident type to create relationships, entities, or observables is extremely tedious. In some cases requiring 15 steps/clicks just to add one object to an Incident!

## Proposed Solution

**Part 1**
- Allow for expanding entities under the Knowledge tabs with Graph View of both Incident Response and Report containers.

**Part 2**
- Add Graph View capabilities to Events of the x-opencti_type: "Incident" and the above bullet point.

## If the feature request is approved, would you be willing to submit a PR?

Willing to support the features via providing documentation. But unable to help with the code due to time.

**Comment by Jipegien** [comment]
Expanding in Knowledge graph could result in adding a lot of entities and relationships and may cause significant damage to the report/case content that cannot be easily reversed currently. 

So we decided to exclude expend feature from Knowledge graph.

But we are providing a way to cover this use case by the following workflow:
- Since 5.10, you can turn the content of a Report/Case Knowledge graph into an investigation graph in one click, where you will be able to expand everything you want without damaging the content of your Report/Case.
- When satisfied with your investigation, you will soon (5.11) be able export the "content" of your investigation graph into a new or existing Report/Case

This workflow covers your use case but also the use case of an analyst receiving external report/case and building its investigation from it.
