### ISSUE TITLE
OpenCTI performing mass S3 List API requests

### ISSUE THREAD

**Issue by leetn00b** [LuatixHQ/opencti#4550]
## Description

We are tracking an issue in OpenCTI version 5.10.2 where the OpenCTI Platform's ECS task is calling the AWS S3 List API 197,000 times in under an hour for the minio S3 bucket. This seems to be related to the path `import/External-Reference/`. This is causing higher than expected costs for us in AWS.

**Comment by ckane** [comment]
Which connectors do you have installed?

**Comment by SamuelHassine** [comment]
Hello @leetn00b,

This can be linked to an enrichment connector querying more than expected (including files) and triggered many times. You are not the only one to have the problem of high AWS costs due to S3 query from OpenCTI.

This will definitely be solved in #4583. We will do our best to prioritize it.

Kind regards,
Samuel
