### ISSUE TITLE
Vulnerabilities are not imported (wrong type for x_opencti_base_score)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4630]
## Description

Vulnerabilities are not imported (wrong type for x_opencti_base_score)

**Comment by sudesh0sudesh** [comment]
Hey Samuel; I can still see the issue. I am unable to find the issue in the code but for some reason, I am still experiencing the issue. Attaching the screenshot. It appears to be particular to floating point score givent to vulns. Additionally i have found that x_opencti_base_score in graphql code is a float; not sure exactly what is causing the issue.
![Uploading Screenshot 2024-01-24 at 18.40.54.png…]()

**Comment by sudesh0sudesh** [comment]
<img width="1784" alt="Screenshot 2024-01-24 at 18 40 54" src="https://github.com/OpenCTI-Platform/opencti/assets/11227791/9d21dc02-6d2b-4362-9810-adabb1c9b407">

**Comment by sudesh0sudesh** [comment]
It might be due to this issue in /src/modules/attributes/stixDomainObject-registrationAttributes.ts: as it specifies as precision integer

{ name: 'x_opencti_base_score', label: 'Base score', type: 'numeric', precision: 'integer', mandatoryType: 'no', editDefault: false, multiple: false, upsert: true, isFilterable: true },

**Comment by SamuelHassine** [comment]
Linked to #5676. Will be fixed in the upcoming release by @richard-julien.
