### ISSUE TITLE
Cannot save changes to report content. Update button is inactive

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4694]
## Description

Cannot save changes to report content. Update button is inactive.

## Environment

1. OS: Ubuntu 20.04.6
2. OpenCTI version: OpenCTI 5.10.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Report->Knowledge->Content mapping view
4. Switch to Edition mode
5. Make some changes
6. The Update button is not clickable

## Expected Output

Update button is clickable.

## Actual Output

Update button is not clickable.

## Screenshots
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/f31ec9bb-0326-4563-8a60-e3a6d2559f38)

**Comment by labo-flg** [comment]
Bug confirmed in latest version (5.11.6) ✅

This happens when the option _Enforce References_ is enabled for the report entity type by an admin.

**Workaround**
* If you only need to update the _description_, you can go through the burger menu (vertical dots next to the report name) and change it from the edition panel. The "Update" buttons works fine there.
* Unfortunately I did not find any workaround for the _Content_ field, as it is only present in the main view.
* disabling the option _Enforce References_ for the reports would also solve the issue but I understand it might be not suitable for you

**RCA**
Once the option _Enforce References_ is enabled, it enables the `<CommitMessage />` inside `<ContainerContent />`
--> see [here](https://github.com/OpenCTI-Platform/opencti/blob/88ebeb32a6a9c50a1d5bdf70284ba4e31ad68919/opencti-platform/opencti-front/src/private/components/common/containers/ContainerContent.jsx#L389)

The button stays disabled here because of the form validation. 
It expects 2 fields that are not present in the form : `name` and `published`.

The form validator comes from the utility function `useYupSchemaBuilder` 
--> see [here](https://github.com/OpenCTI-Platform/opencti/blob/88ebeb32a6a9c50a1d5bdf70284ba4e31ad68919/opencti-platform/opencti-front/src/utils/hooks/useEntitySettings.tsx#L70)

**Additional information**
Same bug when editing a **Grouping** or **RFI** with _Enforce References_. 
* RFI --> the form expects `created` and `name` fields,  not  present in this form.
* Grouping --> the form expects `context` and `name` fields,  not  present in this form.

**Comment by rattat0r** [comment]
@labo-flg Thank you very much!
