### ISSUE TITLE
Failed TAXII Ingester ingestion (CISA AIS 2.0)

### ISSUE THREAD

**Issue by biastogit** [LuatixHQ/opencti#4767]
## Description

Taxii Ingester for CISA AIS 2.0

## Environment

1. OS (where OpenCTI server runs): { k8s }
2. OpenCTI version: { 5.11.11 }
3. OpenCTI client: { frontend }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { Configure the Ingester with certificate authentication }
2. { Add the TAXII server URL + collection ID }
3. { Start the Ingester }

## Expected Output

Entities provided in json response should be ingested in OpenCTI

## Actual Output

Internal Server Error output

## Additional information

{"category":"APP","error":{"context":{"category":"business","data":{"key":"current_state_cursor","operation":"replace","value":[1]},"field":"current_state_cursor","http_status":500,"message":"Attribute current_state_cursor must be a string","reason":"Invalid field current_state_cursor"},"message":"Validation error","name":"ValidationError","stack":"ValidationError: Validation error\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ValidationError (/opt/opencti/build/src/config/errors.js:134:49)\n    at validateAndFormatSchemaAttribute (/opt/opencti/build/src/schema/schema-validator.ts:93:17)\n    at /opt/opencti/build/src/schema/schema-validator.ts:147:7\n    at Array.forEach (<anonymous>)\n    at fn (/opt/opencti/build/src/schema/schema-validator.ts:145:16)\n    at telemetry (/opt/opencti/build/src/config/tracing.ts:63:12)\n    at validateFormatSchemaAttributes (/opt/opencti/build/src/schema/schema-validator.ts:150:10)\n    at fn (/opt/opencti/build/src/schema/schema-validator.ts:268:11)\n    at telemetry (/opt/opencti/build/src/config/tracing.ts:63:12)\n    at validateInputUpdate (/opt/opencti/build/src/schema/schema-validator.ts:280:10)\n    at updateAttributeMetaResolved (/opt/opencti/build/src/database/middleware.js:1807:9)\n    at patchTaxiiIngestion (/opt/opencti/build/src/modules/ingestion/ingestion-taxii-domain.ts:39:19)\n    at taxiiV21DataHandler (/opt/opencti/build/src/manager/ingestionManager.ts:231:5)"},"level":"error","message":"[OPENCTI-MODULE] Taxii ingestion execution error for CISA","timestamp":"2023-10-26T09:17:39.723Z","version":"5.11.11"}

**Comment by SamuelHassine** [comment]
Solved by the last commit. Will be in 5.11.12.

**Comment by richard-julien** [comment]
For people reading this, TAXII 2.1 specification is clear about this parameter must be a string and not a number.
We have setup a workaround to force it as a string to support wrong api implementation

**Comment by greggel** [comment]
Can someone confirm what it was that the TAXII 2.1 specification was clear about being a string and not a number and what the fix was for this?  I am experiencing something very similar to this but not sure if it is the same error

`{"category":"APP","error":{"context":{},"message":"error:05800074:x509 certificate routines::key values mismatch","name":"Error","stack":"Error: error:05800074:x509 certificate routines::key values mismatch\n    at setKey (node:internal/tls/secure-context:93:11)\n    at configSecureContext (node:internal/tls/secure-context:179:7)\n    at Object.createSecureContext (node:_tls_common:116:3)\n    at Object.connect (node:_tls_wrap:1763:48)\n    at Agent.createConnection (node:https:170:22)\n    at Agent.createSocket (node:_http_agent:340:26)\n    at Agent.addRequest (node:_http_agent:288:10)\n    at new ClientRequest (node:_http_client:337:16)\n    at Object.request (node:https:378:10)\n    at hA._performRequest (/opt/opencti/build/node_modules/follow-redirects/index.js:296:24)\n    at new RedirectableRequest (/opt/opencti/build/node_modules/follow-redirects/index.js:69:8)\n    at Object.request (/opt/opencti/build/node_modules/follow-redirects/index.js:535:14)\n    at asyncExecutor (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:451:21)\n    at /opt/opencti/build/node_modules/axios/lib/adapters/http.js:143:5\n    at new Promise (<anonymous>)\n    at wrapAsync (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:123:10)\n    at http (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:161:10)\n    at dJt.dispatchRequest (/opt/opencti/build/node_modules/axios/lib/core/dispatchRequest.js:49:73)\n    at dJt.request (/opt/opencti/build/node_modules/axios/lib/core/Axios.js:146:33)\n    at dJt.Sre.<computed> [as get] (/opt/opencti/build/node_modules/axios/lib/core/Axios.js:172:17)\n    at Function.wrap [as get] (/opt/opencti/build/node_modules/axios/lib/helpers/bind.js:5:15)\n    at taxiiHttpGet (/opt/opencti/build/src/manager/ingestionManager.ts:227:61)"},"level":"error","message":"[OPENCTI-MODULE] Taxii ingestion execution error for CISA AIS PFTE","timestamp":"2023-12-18T21:23:41.078Z","version":"5.12.4"}`

**Comment by richard-julien** [comment]
Looks like very different. More an SSL connection problem `certificate routines::key values mismatch`
Maybe an invalid ssl certificate
