### ISSUE TITLE
Create indicators from external CSV and TXT files

### ISSUE THREAD

**Issue by softengsistemas** [LuatixHQ/opencti#4907]
We want create indicators from external CSV and TXT files like these feeds from MISP (https://www.misp-project.org/feeds/#default-feeds-available-in-misp) located here:
- https://blocklist.greensnow.co/greensnow.txt
- https://rules.emergingthreats.net/blockrules/compromised-ips.txt
- https://api.cybercure.ai/feed/get_url?type=csv

How can I get it?

**Comment by nino-filigran** [comment]
Hi @softengsistemas 
For CSV feeds, we already have this [issue](https://github.com/OpenCTI-Platform/opencti/issues/4569) to tackle, that will exactly match your need
For .txt files, we do not have yet a solution, nor a feature planned. For now, the only manner is either to do it manually or to use our [Import Document connector ](https://docs.opencti.io/latest/usage/import-files/?h=im) . However you'll need to do it each time you have a new file. If in the future, we'll develop a .txt feed, we'll link your ticket so that you will be able to keep track of delivery.
