### ISSUE TITLE
Display bug on knowledge graph overlay when chevrons are present

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5369]
## Description

When chevrons (<>) are present in the name of an entity, the name displayed when hovering over it is not correct:
- if chevrons "<...>" are present, the characters between the two will not be visible
- if only the "<" chevron is present, everything after it will not be displayed
- if only ">", no problem

cf screenshot

## Environment

OCTI 5.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Report and go on the knowledge tab
2. Add in the graph an entity with the name "this<is>atest" and another one named "and<anothertest"
3. Move the mouse over these entities in the graph
-> You can read "thisatest" and "and"

### Bug 

<img width="279" alt="Screenshot 2024-01-04 001206" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/31edc1bd-b011-44ef-a0bc-19ffaa901b8a">

<img width="277" alt="Screenshot 2024-01-04 001223" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/fdab952f-8a0f-4972-a253-7c745469c921">

<img width="399" alt="Screenshot 2024-01-04 001330" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/b8216250-b069-4704-9f76-39ffd90ab8c7">

### No bug

<img width="229" alt="Screenshot 2024-01-04 001215" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/030cbea5-46f6-4567-abdb-8d0b9aecde3a">

**Comment by nino-filigran** [comment]
I do not get the same results than you do, but still have similar issues: 
- case when I create "thisisatest": I see "thisisatest" as expected
- case when I create "<thisisatest": I see an empty black box (as if the entity has no title)
- case when I create "< thisisatest > " (I had to format it with space in the comment to make it appear, otherwise, it disapears): I see "null" as a value
- case when I create "thisisatest>" I see "thisisatest>null"

**Comment by Kedae** [comment]
The problem is from the library we use inject the name directly in the DOM that interprets the < > as HTML.
The solution is to do a new Tooltip of our own to print correctly the name.

This is a non-urgent bug.
