### ISSUE TITLE
Can't I make the Data tab of a report invisible to users?

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#5579]
OpenCTI version: OpenCTI 5.12.20

I don't remember exactly which version, but in a previous version, **the Data tab was not visible in the report for external user, obviously.**

So I was able to upload and manage confidential files related to the report.

But now I see that the Data tab of the report is now accessible to external users.

I've attached a screen shot below for your reference.

_**[Role of External user]**_
![oc](https://github.com/OpenCTI-Platform/opencti/assets/19428462/3647c09b-942c-4c05-82c6-2c06f8e90e0a)

_**[Screen which external users can see]**_
![nv](https://github.com/OpenCTI-Platform/opencti/assets/19428462/488955ab-bcb1-4d8a-9932-c176c8bc34eb)

Did I set the Role incorrectly?

Please check it out and reply a message.

Thanks :)

**Comment by Jipegien** [comment]
The access to entity's tabs is not controlled by capabilities. All the tabs of the entity should be seen as a specific way to display information/knowledge about this entity. 

Data segregation is done at Entity level through marking definition or organization sharing. 

In order to "hide" files for some users, you must associate them with an entity/container that has a superior marking definition than those users or an entity/container that are not shared with the users' Organization (if you have activated this mode).
