### ISSUE TITLE
[backend] Invalid TAXII header when collection is exposed to public

### ISSUE THREAD

**Issue by mrd7790** [LuatixHQ/opencti#5621]
I use taxii2client.v21 to receive data from OpenCTI, but when receiving the objects from the collection, I get the following error. Has anyone had this problem? I will be happy to help

from taxii2client.v21 import Server, Collection

server = Server(url='http://192.168.204.114:8080/taxii2/', user='user', password='password')
collection_id = '3c42e325-611e-43ae-b789-3f2f8f275596'

api_root = server.api_roots[0] 
print(api_root.collections)

desired_collection = None
for collection in api_root.collections:
    if collection.id == collection_id:
        desired_collection = collection
        break
response = desired_collection.get_objects()
print(response)

[<taxii2client.v21.Collection object at 0x7f5b2b4e15a0>, <taxii2client.v21.Collection object at 0x7f5b2b4e1c60>]
Traceback (most recent call last):
  File "/home/mrd/TAXII_Server/server 4/cti-taxii-client/test.py", line 21, in <module>
    response = desired_collection.get_objects()
  File "/home/mrd/TAXII_Server/server 4/cti-taxii-client/venv/lib/python3.10/site-packages/taxii2client/v21/__init__.py", line 376, in get_objects
    return self._conn.get(self.objects_url, headers={"Accept": accept}, params=query_params)
  File "/home/mrd/TAXII_Server/server 4/cti-taxii-client/venv/lib/python3.10/site-packages/taxii2client/common.py", line 319, in get
    raise TAXIIServiceException(msg.format(content_type, accept))
taxii2client.exceptions.TAXIIServiceException: Unexpected Response. Got Content-Type: 'application/json; charset=utf-8' for Accept: 'application/taxii+json;version=2.1'
If you are trying to contact a TAXII 2.0 Server use 'from taxii2client.v20 import X'
If you are trying to contact a TAXII 2.1 Server use 'from taxii2client.v21 import X'

and

from taxii2client.v21 import Server, Collection

server = Server(url='http://192.168.204.114:8080/taxii2/', user='user', password='password')
collection_id = '3c42e325-611e-43ae-b789-3f2f8f275596'

api_root = server.api_roots[0] 
print(api_root.collections)

desired_collection = None
for collection in api_root.collections:
    if collection.id == collection_id:
        desired_collection = collection
        break
response = desired_collection.get_objects(accept='application/json; charset=utf-8')
print(response)

[<taxii2client.v21.Collection object at 0x7fce28bed600>, <taxii2client.v21.Collection object at 0x7fce28bedcc0>]
Traceback (most recent call last):
  File "/home/mrd/TAXII_Server/server 4/cti-taxii-client/test.py", line 21, in <module>
    response = desired_collection.get_objects(accept='application/json; charset=utf-8')
  File "/home/mrd/TAXII_Server/server 4/cti-taxii-client/venv/lib/python3.10/site-packages/taxii2client/v21/__init__.py", line 376, in get_objects
    return self._conn.get(self.objects_url, headers={"Accept": accept}, params=query_params)
  File "/home/mrd/TAXII_Server/server 4/cti-taxii-client/venv/lib/python3.10/site-packages/taxii2client/common.py", line 319, in get
    raise TAXIIServiceException(msg.format(content_type, accept))
taxii2client.exceptions.TAXIIServiceException: Unexpected Response. Got Content-Type: 'application/json; charset=utf-8' for Accept: 'application/json; charset=utf-8'
If you are trying to contact a TAXII 2.0 Server use 'from taxii2client.v20 import X'
If you are trying to contact a TAXII 2.1 Server use 'from taxii2client.v21 import X'

**Comment by helene-nguyen** [comment]
Hello @mrd7790,

We will check it out, but first I have a few questions for you:
- Which version of OpenCTI do you use ? 
- Could you give us small steps to reproduce this error ?

**Comment by trialsgama** [comment]
Hi Helene,

As we had talked in opencti-dev chat, i am adding the steps to reproduce this error.

![step_1](https://github.com/OpenCTI-Platform/opencti/assets/39866246/abc488c2-6757-49cd-bdf5-bd89fdb91831)
![Step 2](https://github.com/OpenCTI-Platform/opencti/assets/39866246/363481e3-2036-45c6-8f1e-e3351b25f847)
![feed](https://github.com/OpenCTI-Platform/opencti/assets/39866246/ef3418ca-11b5-4a6b-866d-4476d9892902)
![feed_2](https://github.com/OpenCTI-Platform/opencti/assets/39866246/7d179006-f297-4aed-b9a1-f73fc9aba786)
![objects](https://github.com/OpenCTI-Platform/opencti/assets/39866246/612ffbef-4bb6-4612-be6d-ab0693a58dd2)

When this is created, the response from opencti in content-type changes due to apollo server embebed on graphql library and it overwrite the previous header

Request to taxii discovery responses with correct header

![image (2)](https://github.com/OpenCTI-Platform/opencti/assets/39866246/ba8e0917-3e95-49b1-80e3-4a89b29a671a)

Request to feed responses in an incorrect way

![image (6)](https://github.com/OpenCTI-Platform/opencti/assets/39866246/3af543a5-69ee-4973-85d6-fb5db384a25e)

![image (5)](https://github.com/OpenCTI-Platform/opencti/assets/39866246/64a12fd1-cb40-4adb-9c27-bfef7ec497c6)

![image (4)](https://github.com/OpenCTI-Platform/opencti/assets/39866246/58224072-19ad-4eee-a83e-ac4f4f6048dd)

**Comment by helene-nguyen** [comment]
Hello @mrd7790, @trialsgama, I need to check with the team, I'll give you an update as soon as possible !

**Comment by helene-nguyen** [comment]
By the way, I reproduced the steps you gave, I got the same response:

![image](https://github.com/OpenCTI-Platform/opencti/assets/75518128/761a2f03-cd89-46f2-ac7c-51b2ad966e9a)

**Comment by helene-nguyen** [comment]
Hello @mrd7790 , @trialsgama, after investigations, a PR is opened to fix the header :)

**Comment by mrd7790** [comment]
@helene-nguyen 
tnx :)
