### ISSUE TITLE
[file indexing] infinit retry on parsing

### ISSUE THREAD

**Issue by pierremahot** [LuatixHQ/opencti#5629]
## Description

The indexing process retry on error when elastic respond an error on parsing the file

## Environment

1. docker / kube
3. OpenCTI version: 5.12.20
4. OpenCTI client: frontend

## Reproducible Steps

1 start idexing
2 get error with elastic (don't know the exact cause can be no available heap related)

## Expected Output

do not infinite retry

## Actual Output

infinite retry.
this also restart the manager and update startup date of the manager.
get big logs because of the base 64 of the file send to the logs.

**Comment by richard-julien** [comment]
Multiple problems here:
- When a file fail indexing, the process retry every minute on the same file
As we cant do anything, we only need to log the error instead of throw.

- When a file fail indexing in elastic, we throw and log too much
Instead of throw we will log (point 1) but we need to log the error without the body content as it contains the file in base64.
