### ISSUE TITLE
Connectors should not be listed as potential assignees when creating a new report

### ISSUE THREAD

**Issue by gusandrews** [LuatixHQ/opencti#5770]
## Description

Connector users currently appear in the "assignees" dropdown list when a user creates a new report.

_As a member of a team using OpenCTI to share threat reports
I need to be able to quickly see the humans on my team who I can assign to when creating a new report
So that I do not get confused by non-human users on the list, or overwhelmed by the number of options in this list._

## Environment

1. Mac OS 14.3
2. OpenCTI version: 5.11.12
3. OpenCTI client: frontend
4. Other environment details: Chrome browser

## Reproducible Steps

Create connector user(s) for an instance of OpenCTI.
In Analyses > Reports, click the "create report" plus button in the lower right.
The "Create a report" modal popup dialogue appears.
Click "Assignee(s)."

## Expected Output

Because connector users are not actually people, they should not appear in this list.

## Actual Output

Your connector user(s) are visible can be selected as assignees for this report. 

## Screenshots (optional)

<img width="1205" alt="Screenshot 2024-01-31 at 4 24 04 PM" src="https://github.com/OpenCTI-Platform/opencti/assets/1565981/7266cddb-e66e-4ee9-b144-0b58aa3cef23">
<img width="739" alt="Screenshot 2024-01-31 at 4 19 48 PM" src="https://github.com/OpenCTI-Platform/opencti/assets/1565981/696a290a-2865-46d9-8a93-e86cde678fef">

**Comment by nino-filigran** [comment]
@gusandrews I understand your issue, but this is not a bug. As you have mentioned, even if they are not real persons, they are still users, and by default you can assign any user as assignee. This is done by design. We can however think about this if it's a real issue, but so far, we have not hear any feedback in that sense, since people usually know what users they have in the platform.
