### ISSUE TITLE
SSO OpenID groups mapping

### ISSUE THREAD

**Issue by lhviet** [LuatixHQ/opencti#6186]
## Use case

I would like to leverage the OpenID Connect option of Authentication.
I have custom groups and have previously added users manually into OpenCTI groups. I’d like to map OpenID groups to OpenCTI groups so that when users login and authenticate, they are automatically put into OpenCTI groups. However, in the process, I face several issues that block us from using the group mapping feature.

**Problem:**
If a user is mapped through group mapping, and I want to change that user’s group manually, it will be overwritten whenever they log in.
If a user belongs to 2 groups and they are both mapped, we cannot choose if the user maps to group 1 or group 2.
Creating multiple groups for granular permission controls is expected, but too many groups make our lives difficult.

I am not sure what is the best solution. But it is great if we can figure out how to make our lives easier.

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by Jipegien** [comment]
Hello @lhviet! Not sure to understand the need. Correct me if I'm wrong:
- You are able to map users to groups in OpenCTI based-on data coming from OpenID SSO
- Any modification of this mapping into OpenCTI is overwritten after a new login. That's because your SSO is considered as the source of truth.
- if openID define a user to be part of 2 groups, then in OpenCTI only one group is mapped to the user ?

**Comment by nino-filigran** [comment]
Closing this ticket given that there was not any response so far. @lhviet Please feel free to reopen it if you need to talk about this in more details.
