### ISSUE TITLE
Bad behavior on top search bar

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6260]
## Description

1. Click inside the top search bar
2. Click elsewhere in the screen (not on a button or another link) => it redirects to advanced search

## Expected Output

The search should only be triggered when clicking on the search icon or if the key "enter" is pressed

**Comment by jpkha** [comment]
We discussed we @Kedae, that we add a functionality where the search is triggered "onBlur" when leaving the input.
I can make a parameter to activate or deactivate this functionality depending on which case we are using.
For now, I have fixed the issue, we do not submit anything if the value in input did not change, but we still have the submit "onBlur".

**Comment by Kedae** [comment]
Well I think we misunderstood each other.

My point was the following : we need the searchInput to be correctly cleared when clearing filters.
The bonus point was : if we are able to update the localStorage onBlur without triggering the query, we should do it to gain consistency.

That being said, I'm not really sure what is the problem here @SamuelHassine, lot of tools (Notion for example, or our own docs) search when typing, onBlur or stuff like that not depending on a "enter" click. If it allows us more consistency and simpler interaction why should we rollback ?

**Comment by Kedae** [comment]
@jpkha additionnaly, the clear on search panel doesn't clear the input

**Comment by jpkha** [comment]
My point here is simply that we add the onBlur capability to ensure consistency. @SamuelHassine may not have been aware of this. I believe it would be clearer to submit a query upon leaving the search input because, in my opinion, having a search within the input but not applied to the list can confuse the user.

But let me know if you prefer to update the localStorage without triggering the query, as it is also possible.

**Comment by Jipegien** [comment]
the onBlur should not trigger the query. (Seen with Adrien)
