### ISSUE TITLE
Background tasks trigger multiple multiple history events instead of one

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6295]
## Description

1. Update the author of a list of entities via a background task

Result in history:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/73faa329-4e77-4d41-b639-2cc8f44b86be)

The replace "nothing" is incorrect.

**Comment by marieflorescontact** [comment]
`Author` is a relation so it is deleted then recreated by` taskmanager`. That's why we have 2 events. What can we do to prevent this in your opinion @SamuelHassine ? 
see: `taskmanger.js > executeReplace()`

Is it only message clarity problem? we can replace :
`admin replaces nothing in  Author`  by ` admin removes  value  in Author `

**Comment by SamuelHassine** [comment]
No, I think this is an event problem, it should not generate a remove / create. Check with @Kedae please.

**Comment by marieflorescontact** [comment]
any thoughts on that @richard-julien ?

**Comment by richard-julien** [comment]
Looking the code maybe the problem is the manager is not using the new capabilities of the patch function.

The current code is like this
 ```
 if (contextType === ACTION_TYPE_RELATION) {
    // 01 - Delete all relations of the element
    const rels = await listAllRelations(context, user, field, { fromId: element.id });
    for (let indexRel = 0; indexRel < rels.length; indexRel += 1) {
      const rel = rels[indexRel];
      await deleteElementById(context, user, rel.id, rel.entity_type);
    }
    // 02 - Create new ones
    for (let indexCreate = 0; indexCreate < values.length; indexCreate += 1) {
      const target = values[indexCreate];
      await createRelation(context, user, { fromId: element.id, toId: target, relationship_type: field });
    }
  }
```
And i suppose that the ACTION_TYPE_RELATION is in fact only related to ref relationships.

With latest platform improvements, the patch function shoud now support to do ref replace directly.

`await patchAttribute(context, user, element.id, element.entity_type, patch);`

So for me the first part of the code must be removed / migrate to also use the patchAttribute function.
