### ISSUE TITLE
"is not empty" operator does not work on CPE attribute

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#6517]
## Description

Filtering Softwares with "cpe is not empty" list Software with empty CPE.

**Comment by Archidoit** [comment]
The filter 'is not empty' is working. The problem is that the 'cpe' attribute is equal to "" (empty string) when it is undefined, instead of being really equal to null/undefined. Same problem for other fields (like swid, vendor, version, etc for Softwares).

We can either:
- make the 'is not empty' operator take empty string into account
- migrate empty string to null value + setting null value to those fields at software creation/edition instead of empty string

Chosen solution (validated with @Jipegien ) : make the 'is not empty' operator take empty string into account

**Comment by Archidoit** [comment]
Same issue with date filters (test 'last seen is empty' on malwares via the API)
