### ISSUE TITLE
Widgets that use the entity color might end up unreadable

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#6521]
If you create a Donut widget on markings, the widget will use the color of the markings as colors inside the chart.

Howevre, the labels in the tooltips are rendered on top of this fixed color, and it might end up white-on-white which is unreadable.

![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/b6cc2c3e-ac73-405f-93bf-856bcd35f989)

**Comment by lndrtrbn** [comment]
This one is a bit tricky as the lib ApexChart does not offer in its API the possibility to change text color in tooltip. You need to either target the text in the tooltip with CSS or create a complete custom tooltip.

I don't think the CSS targeting solution will work because we cannot define dynamically the color depending on the data we are hovering in the chart. So it means recreate a complete tooltip. We can take advantage of this solution to create a tooltip that looks more like the other tooltips we have in the app with OpenCTI UI.
