### ISSUE TITLE
Leaked Tokens are not revokable

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#6643]
## Environment
1. OS (where OpenCTI server runs): debain (k8s)
2. OpenCTI version: 6.0.9

## Description
If an access token is leaked there is no possibility to revoke it or to generate a new one. The only possibility that exists is to delete the user and generate a new one. But with this approach the complete history gets lost (not associated) because it is not associated with the new user.

## Solution
A user has not automatically a token assigned. There exists the possibility for the user and for an admin to create a token. If the token is leaked the user or the admin can revoke the token (if deleting is enough depends on the current auth implementation, idk) and generate a new one, if necessary.

**Comment by nino-filigran** [comment]
@iFrozenPhoenix Thanks for your request. As you have seen, I've modify your ticket since we consider this being a feature, given the fact that it's a behavior that does not exists currently in the platform and not something that is broekn. I agree though that it's a must and shoul dbe there as a feature.

**Comment by nino-filigran** [comment]
@aHenryJard thanks for having solved this! I'm re-opening the issue because an orgn admin cannot manage its own user's token.
Use case:
- I'm an org admin in a org segregation 
- one of my user has a leaked token 
- I want to be able to reset it instead of asking to the main platform org.

However this feature that you delivered already provided some increased security & is a great addition. Do you think I should  rather create a new feature for this? Or keep this one open? Indeed, I don't want to prevent the release of this!

**Comment by labo-flg** [comment]
@nino-filigran you should probably create another issue for that specific use-case related to orga segregation.

**Comment by nino-filigran** [comment]
Ok, created it here: https://github.com/OpenCTI-Platform/opencti/issues/8819
