### ISSUE TITLE
Frontend not updated properly when adding a user to a group

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6703]
## Description

1. Go to a group
2. Open edition
3. Go in members
4. Check a box

=> The box is never checked, you have to full refresh

**Comment by labo-flg** [comment]
I stumbled upon this bug recently, here's some insights: 
* The query is sucessful
* frontend has issues with duplicated keys in the user list in `GroupEditionUsers`, which could explain the UI
* if you refresh, all is ok.
* if you DONT refresh and go to the page groups, you'll get an error. In fact you'll get an error everywhere in the app: relay is basically crashed because of interlaced updater calls (the error logs points to the updater in `GroupEditionUsers`, on the add user mutation

**Comment by Archidoit** [comment]
Yes, the problem comes from the updater that throws an error (because incorrect pagination options are given).
