### ISSUE TITLE
PDF export of content in HTML is not working anymore

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6773]
## Description

PDF export of content in HTML is not working anymore.

1. Go to https://filigran.octi.filigran.io/dashboard/analyses/reports/39c5dfd8-aa33-4ada-ac62-cc405ad0d821/content?
2. Click on PDF in the bottom bar

=> Nothing happens.

(same with all type of content / even just one word).

**Comment by CelineSebe** [comment]
No issue in the local environment, tested

**Comment by lndrtrbn** [comment]
Can reproduce by exporting the file in the link and uploading it locally. I take the issue

**Comment by lndrtrbn** [comment]
Issue: applying an other font than Default breaks the PDF export

**Comment by lndrtrbn** [comment]
Did the possibility to change fonts work at some point in the past? 
We do not have those fonts defined anywhere in our static files so pdfmake cannot use them. 
We have them because available in the editor because of some default CKEditor config I guess but to make the PDF export working we need to specify how to fetch them.

Should be fixable by:
- adding manually those fonts in our static folder aside our Roboto fonts,
- maybe link fonts resources used by CKEditor in node_modules but not sure it will work.

Does the possibility to change fonts is necessary? Easy fix: remove the font family button from editor.

**Comment by nino-filigran** [comment]
@lndrtrbn are you expecting any answer from anybody on this ticket?

**Comment by lndrtrbn** [comment]
Well yes 😂

**Comment by lndrtrbn** [comment]
From discussions:

- disabling the button to change the font family is not a solution as we can copy paste anything so even without the buttons to change font family we could still copy paste custom font
- so still manage fonts in content editor. In export, ideally use the font if recognize otherwise use default, but if not possible use default font anytime
