### ISSUE TITLE
[Marking restriction] History can lead to data leak

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6785]
## Description

If access to an entity is restricted for a user who doesn't have the appropriate allowed marking, it's possible that he'll still be able to see the entity's name in the relationship's "History".

## Environment

OCTI 6.0.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. User A is admin with full access
2. User B is read only user with full access except TLP:RED
3. With user A: Create A campaign AAA TLP:CLEAR with a relation to a Threat actor BBB TLP:RED
4. With user B, look at campaign AAA
-> You will see one relation with a threat actor but it will be restricted. However, by going in the History tab, you will see the threat actor related to the campaign (see screenshot)

### This is expected, ok
![Screenshot 2024-04-22 164457](https://github.com/OpenCTI-Platform/opencti/assets/70956706/f28e23a5-1d0c-4588-8045-fb583ece8a05)

### But this is a problem
![Screenshot 2024-04-22 164448](https://github.com/OpenCTI-Platform/opencti/assets/70956706/266237b3-4afa-4df9-8668-d681b9600580)

**Comment by nino-filigran** [comment]
Found a linked bug (not critical): https://github.com/OpenCTI-Platform/opencti/issues/6787

**Comment by richard-julien** [comment]
The history message is currently generated directly from event independently from the user rights.
This message is sent to the stream and writen in the history as it.
Changing the message will be complex as it will required to be generated on demand when client asking for the history depending of his ACL.

A first approach could be to merge the markings of the to/from inside the markings of the relation in the history instance. 
This way the complete line will be hidden in this kind of situation

In my memories it was already the expected behavior so are you sure @Lhorus6 you have created the relationship directly with a marking not available for this user?

**Comment by nino-filigran** [comment]
After checking, it depends on the order that you perform the operation.

**Comment by Lhorus6** [comment]
The history is a kind of snapshot of the situation at a given moment. The history therefore has the marking that was applied to the information at the time the action took place. If the entity that is restricted today was accessible to the user at the time of the action, the user can see this history.
