### ISSUE TITLE
Incorrect sighting overview path

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6786]
## Reproductible steps
- Go to the sightings list
- Click on a sighting

The redirection is not correct (we should be redirected in the 'sightings' tab of the concerned entity)

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/9d780d6d-9795-4052-b632-31ee255fa746)

## Comment
See redirection of stix core relationship, that is correct:
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/d8623c3a-47a4-4122-8e97-35860c0c3461)

**Comment by nino-filigran** [comment]
@Archidoit even though this behavior is not consistent in the app, this is the desired behavior. We even have a task to change the relation overview screen which is currently confusing (since we see relations in the context of entities, which is misleading). https://github.com/OpenCTI-Platform/opencti/issues/5007 

As a result, I'm closing this bug since we won't work on it.
