### ISSUE TITLE
Wazuh logs to open CTI

### ISSUE THREAD

**Issue by KhaledEid020** [LuatixHQ/opencti#6800]
## Description

Is there anyway to integrate Wazuh with OpenCTI?
I need form OpenCTI to stream all the logs coming from Wazuh so we can use the case management feature that exist in OpenCTI.

What I found after searching, is OpenCTI sending IOC's to Wazuh, but I didn't see the opssite

**Comment by ghost** [comment]
@KhaledEid020 you can do it like described here https://wazuh.com/blog/using-wazuh-and-thehive-for-threat-protection-and-incident-response/.
This example is for the Hive but also usable with opencti.
Instead of the custom-w2hive.py you can create the case like in this example https://github.com/OpenCTI-Platform/client-python/blob/master/examples/create_incident_with_ttps_and_indicators.py.

Hint: I'm just a User.

**Comment by Jipegien** [comment]
https://github.com/OpenCTI-Platform/connectors/issues/992
