### ISSUE TITLE
Update CSV mapper to improve TTP mapping 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#6813]
## Use case
Currently, we have issues using CSV mapper for Attack patterns: 
- deduplication is based on Name & x_mitre_id" (aka External ID).
- the field external ID is not mappable in the CSV mapper

As a result, TTPs are duplicated in the platform.

## Current Workaround

None
## Proposed Solution

Introduce the field external ID in CSV mapper. 

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by nino-filigran** [comment]
It seems that the Deduplication mechanism does not take the field external id if not included (ex: TTP A has title test and TTP B has title test and description = this is a TTP. Both do not have an external ID). As a result, the current deduplication mechanism would deduplicate A and B. @Lhorus6 to confirm that this seems alright

**Comment by Lhorus6** [comment]
The deduplication work if:
- Name = "XXX"
- x_mitre_id is empty (I guess that for the platform, "empty = empty" so the deduplication run).

However, it's still a problem because we want to use the MITRE Attack Pattern already in the platform. These have descriptions, all their MITRE information (e.g. courses of action), are linked with Intrusion sets, Malware, etc.

Without the ability to put a x_mitre_id, we create a copy without any info (just the same name) of the MITRE TTP


All connectors create relations with MITRE TTPs. Having a copy of the TTPs does not make sense because we will not be able to identify the threat, retrieve information, mitigation method, etc.
