### ISSUE TITLE
[Workbench] Workbench changes country names after validate import

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6861]
## Description

When my workbench maps a country by its alias (e.g. I have “CA” for Canada), it changes its main name after validating the ingestion (“CA” becomes the main name and “Canada” the alias).

## Environment

OCTI 6.0.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create the country Canada and put "CA" as an alias (maybe it's already in the platform, or maybe you just need to add "CA" in the alias)
2. Go to "Data > Import" and create a workbench (with the "+" in the bottom right corner)
3. Add in the empty workbench the country "CA", you will se that the workbench find it in your platform (normal, CA is an alias for an existing entity)
4. Validate the workbench
5. Check your country "Canada" -> now it's called “CA” and “Canada” is an alias.

## Expected Output

I don't want the name and alias to be switched

**Comment by nino-filigran** [comment]
This is the overall behavior of the merge when you have an alias, the alias will become the entity name. 
Same happens with every entity. Therefore, this is not a bug in essence, but not an optimal behavior for some entities, such as countries, cities, regions, area. 

For this, we have a solution, already in place: you can set **per user an overide of the confidence level per entity type**. As a result, you can (or should?) reduce the confidence level of your users to less than 100 (I tried with 50) and ensure your user don't have the **Bypass** capability. Because your user won't have a sufficient confidence level, the merge won't happen. 
You can try this behavior on **Testing** (I've successfully tested it on France with an Alias FRA). It failed on Canada because even though I4'e reduced my own confidence level on country, I had the bypass the capability.

I'm switching your bug to a question: if you find my answer satisfactory, please close it.

**Comment by nino-filigran** [comment]
@Lhorus6 sorry did not tag you there.

**Comment by Lhorus6** [comment]
Now I understand better! That makes sense, it's true that this was observed when importing information via connectors.

However, we might have something to do here. For connectors, the source overwrite the entity with its information, that's ok.
But in the case of workbenchs, we want to take advantage of the functionality to be able to attach information to entities already existing in the platform without modifying them. When I see “Yes” at the end of the line (which means that the entity exists in my platform), I expect to “use” the existing entity, and not create a new one (new one that will be merged and thus produce this effect).

The current mechanism (in addition to being a little counter-intuitive) makes its use problematic. The platform's administrators also import data, so this problem will be present (in general, administrators are also analysts)
- It's not possible for them to reduce their capacity; they must have admin rights.
- Creating a second account with restricted rights just to be able to do their imports without breaking everything would be really annoying (they'd have to switch from one account to another every time).

**Comment by nino-filigran** [comment]
@Lhorus6 understand your point there.
Given that we don't plan to work on workbench, I don't think we would work specifically on this topic, but would rather tackle it in the context of drafs: we're indeed studying the update of the upsert behavior to at least be able to modify the existing entity instead of upserting an exsiting one with the user's change (edit instead of create & merge) for the exact you mentioned. If we know that the entity already exists, why not prompting the existing entity as is and let user update the fields that are needed instead of creating everything & see if changes are merged or not (given the ACLs).

Given the above response, for now, we'll not change anything. That's an (annoying) workaround that can solve issues and given our roadmap, not something that we can actively work on. 
@Jipegien for awarness.

**Comment by Lhorus6** [comment]
"If we know that the entity already exists, why not prompting the existing entity as is and let user update the fields" -> Exactly!!!

I know that we won't lose any development resources to improve the workbenchs, I understand. If it's well taken into account for the future functionality that will replace them, that's ok with me. Thanks @nino-filigran

A question for the tracability, is it this issue/functionality which will replace the workbench ? https://github.com/OpenCTI-Platform/opencti/issues/3798

**Comment by nino-filigran** [comment]
Yes, that's the one for now!
