### ISSUE TITLE
Last created relationship with a relationship displayed as Unknown

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6865]
- Go to an entity that has a relation with a relationship
- In the entity overview, in the 'last created relationship', the relationship target is displayed as Unknown : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/6c56edca-c5ae-4092-8317-4da8fed9770b)
- In the Knowledge tab, nothing is displayed in the 'name' column : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/dae77189-8b01-461c-81e2-43a725215894)

When we click on the relationship line : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/3eff173d-477b-4ce9-abcc-968ffb46ff9a)

**Comment by nino-filigran** [comment]
@Archidoit I'm not able to reproduce either on Demo or Testing.
I tried with several entities (Malware, Intrusion Sets, IOCs), going into the entity knowledge tab, creating a relation from there. Going back to the entity overview (went to both each time) and everything was displayed well. Can you let me know where/which case did create this issue for you?

**Comment by Archidoit** [comment]
Exemple of steps to reproduce: @nino-filigran 
- On the relationships tab, click on a relationship of type 'uses'
- Add a 'linked entity' of type 'indicator'
- Go to the indicator overview

**Comment by nino-filigran** [comment]
To be clear, about the repro case, please use the "linked entities" as shwon in the screenshot, not the one in the list: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/151ab8af-a93d-49f3-a7a3-1253ce36ca97)


I've been able to reproduce. I think there are couple of things going wrong in here: 
- when selecting the + on linked entities, the look and feel is still the "old one": this is not to be fixed here, since it's a feature not a bug
- when selecting an indicator, the original entity that you want to create appears in an odd way (it looks like we're using a representative), while we should the From Entity exactly like the Target entity 
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/9c1973b0-dc27-46d6-8082-6e9a9f5a083d)
- when going to the indicator's page, it looks like a relation has been created, **but the "to entity" is a relationship type uses instead of an entity** (I my case it was supposed to be an intrusion set)
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/b1d5948c-4fe8-481d-89f3-af386d5b733a)
- when going to the indicator's knowledge tab, the relation does not appear (is it because the relation is not vzalid, since we're creating a relation that points to a relation?
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/46dbc00a-e161-4e2c-a300-192b904d00f3)
- when clicking on the relation, same as the begining, it's odd: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/f434e664-07bf-497f-b5d7-99c9260b8728)
