### ISSUE TITLE
[GraphQL playground] Documentation no longer appears, but playground works

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6992]
## Description

When I'm on the GraphQL playground, the documentation is no longer available (it doesn't load).

NB: But the payground works (when I run queries, it works).

## Environment

OCTI 6.1.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to https://<your_instance>/graphql
2. Click on "Docs" at the right to open the side window, which normally contains the documentation
-> documentation does not load

![Screenshot 2024-05-16 143035](https://github.com/OpenCTI-Platform/opencti/assets/70956706/81697457-a4ba-4d26-8437-ae0271eed5e8)

## Additional information

I also see “Server cannot be reached”, in the top right corner, I don't know if it's related.

![Screenshot 2024-05-16 143028](https://github.com/OpenCTI-Platform/opencti/assets/70956706/137f968b-126f-434d-b646-ac5fa2c6e3c4)

**Comment by SamuelHassine** [comment]
Hello,

GraphQL introspection has been disabled by default following a security review (not the production best practice). To re-enable it, it should be defined in the configuration of the platform.

We can definitely do this in our testing environment to ease the work of everyone.

**Comment by SamuelHassine** [comment]
I've just re-enabled it on https://testing.octi.staging.filigran.io/.

**Comment by SamuelHassine** [comment]
https://docs.opencti.io/latest/deployment/configuration/#technical-customization : APP__GRAPHQL_PLAYGROUND__FORCE_DISABLED_INTROSPECTION

**Comment by SamuelHassine** [comment]
Default is now true.

**Comment by simonbjorzen-ts** [comment]
Tried re-setting the variable to false, but still facing this issue.
On version 6.1.2.

**Comment by Lhorus6** [comment]
If I've understood correctly, you should set it to “true” @simonbjorzen-ts

**Comment by simonbjorzen-ts** [comment]
Same issue with  APP__GRAPHQL_PLAYGROUND__FORCE_DISABLED_INTROSPECTION=true

**Comment by SamuelHassine** [comment]
Hello @simonbjorzen-ts, 

Typo in the doc: `APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION=true` instead of `APP__GRAPHQL_PLAYGROUND__FORCE_DISABLED_INTROSPECTION=true`.

I've fixed the doc.

**Comment by annoyingapt** [comment]
Just to clear up the confusion in the comments. If you want to enable graphql introspection, you need to add the following config:

`- APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION=false`

**Comment by OH-AShymchuk** [comment]
We are also experiencing the endlessly spinning circle/icon when trying to display the SCHEMA on the /graphql workbench. This thread appears to imply that GraphQL Playground Introspection was DISABLED based on another thread request.

https://github.com/OpenCTI-Platform/opencti/issues/6465

Similar to this website...
https://demo.opencti.io/graphql

Company policy requires our team to perform a DAST scan against OpenCTI GraphQL, but we are having a heck of a time with server 500 errors when trying to perform Introspection pull from /graphql. Then, we discovered this thread.

We are using Ubuntu 22.04LTS in Docker with Portainer.

Will adding the following to the docker-compose.env file re-enable this feature so that we can perform a StackHawk GraphGL scan for our Security and Compliance department? (based on the assumption that this may have been disabled for OpenCTI 6.1.12)

APP__GRAPHQL__PLAYGROUND__ENABLED=true
APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION=false

... no matter what combination of true/false we try, we cannot get DOCS or SCHEMA to load.

Any feedback is greatly appreciated.

Thank you for your continued support and development of OpenCTI.
Best...

**Comment by gritty-Kitty** [comment]
We are also experiencing the endlessly spinning circle/icon when trying to display the SCHEMA on the /graphql workbench. This thread appears to imply that GraphQL Playground Introspection was DISABLED based on another thread request.

https://github.com/OpenCTI-Platform/opencti/issues/6465

Similar to this website...
https://demo.opencti.io/graphql

Company policy requires our team to perform a DAST scan against OpenCTI GraphQL, but we are having a heck of a time with server 500 errors when trying to perform Introspection pull from /graphql. Then, we discovered this thread.

We are using Ubuntu 22.04LTS in Docker with Portainer.

Will adding the following to the docker-compose.env file re-enable this feature so that we can perform a StackHawk GraphGL scan for our Security and Compliance department? (based on the assumption that this may have been disabled for OpenCTI 6.1.12)

APP__GRAPHQL__PLAYGROUND__ENABLED=true
APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION=false

... no matter what combination of true/false we try, we cannot get DOCS or SCHEMA to load.

Any feedback is greatly appreciated.

Thank you for your continued support and development of OpenCTI.
Best...

**Comment by gritty-Kitty** [comment]
Whether we use TRUE/TRUE, or TRUE/FALSE, the results are the same. We tried an example query, and receive the following message either way.

GraphQL Introspection not authorized!
FORBIDDEN_ACCESS

Playground was initiated by logging in as Global Admin > Profile > Playground (launch)

![image](https://github.com/user-attachments/assets/16dd12ef-5972-4e0c-a348-906c97007229)
