### ISSUE TITLE
Domain name values should be case insensitive

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7311]
## Description

Create domain 1: Google.com
Create domain 2: google.com

=> Duplicate

**Comment by SarahBocognano** [comment]
What about url, email adress, hostname ? And is there others that are case sensitive ?

**Comment by richard-julien** [comment]
In my memories i have implemented the STIX specification.
They explicitly describe that the data must be canonicalize but nothing about removing the case.

```
The value of the name portion SHOULD be the list of "ID Contributing Properties" (property-name and property value pairs) as defined on each SCO object and SHOULD be represented as a JSON object that is then serialized / stringified according to [
[RFC8785](https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#kvy09cwtcw71)
] to ensure a canonical representation of the JSON data.
```

@SamuelHassine, I think the solution will be to lowercase the value before creating the standard_id instead of changing the way the standard_id is generated.

**Comment by buddycat** [comment]
Not sure if this is the place to comment, but urls can contain case sensitive data (hashes, etc.) that forcing lower casing would break.
