### ISSUE TITLE
Not possible to update a relation between a relation and an attack pattern

### ISSUE THREAD

**Issue by sancievanneaud** [LuatixHQ/opencti#7383]
## Description

The update button is not displaying on a relation between a relation and an attack pattern.

## Environment
OpenCTI version: 6.1.11

## Reproducible Steps

1. Select an Intrusion set, and create a relation "use" with an attack pattern.
2. Go to the overview of the relation
3. In the overview of the relation, click on the + of "linked entities" (to be able to create a relation that has a source the previous relation)
4. create a new relation "related to" another attack pattern (if the attack pattern does not exist in the list of entities, click on the + to create a new attack pattern, it should be added in the right pannel when created)
5. Go on Data / relationship, retrieve the last relation created (relationship related to attack pattern)
6. The update button is not displaying.

## Expected Output

The update button is displaying and you can update this relation.

## Actual Output

4. The update button is not displaying

## Comment
This behavior was confirmed on Filigran internal demo platform and Filigran free demo.
This behavior was not confirmed on a relation between a relation and an another entity like a report.

**Comment by nino-filigran** [comment]
@sancievanneaud I do not reproduce. Did I miss anything?
If not and you do not have this problem anymore, would you mind closing this bug please?

https://github.com/OpenCTI-Platform/opencti/assets/148041607/698bb071-828f-4d18-84a3-1a6816c508b5

**Comment by nino-filigran** [comment]
After dicussion, the bug is clear. Basically, the exact repro case is: 

1. Select an Intrusion set, and create a relation "use" with an attack pattern.
2. Go to the overview of the relation
3. In the overview of the relation, click on the + of "linked entities" (to be able to create a relation that has a source the previous relation) 
4. create a new relation "related to" another attack pattern (if the attack pattern does not exist in the list of entities, click on the + to create a new attack pattern, it should be added in the right pannel when created)
5. Go on Data / relationship, retrieve the last relation created (relationship related to attack pattern)
6. The update button is not displaying.

I've updated the description of the main ticket.

**Comment by Archidoit** [comment]
Similar issue for Data component, Data Source and Course of Action: the relationship is updatable but there is a blank space on the right --> remove paddingRight for those entities

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/0d3e11ce-4a0a-4912-b0cf-ebd4d5540857)
