### ISSUE TITLE
[CSV Mapper] Add ability to ingest multiple types of objects and associated relationships in one file

### ISSUE THREAD

**Issue by sweet-mentat** [LuatixHQ/opencti#7402]
## Use case

This is related to https://github.com/OpenCTI-Platform/opencti/issues/4935 (which I think would be preferable), but I am suggesting a different way of solving the problem. An example would be that I have a list of indicators of compromise - a list of different types of cyber observables - that are associated to a threat actor and campaign. The way the csv mapper works right now, I must create a file and configuration/mapper for each type of cyber observable (yuck). I would like to be able to configure a column per cyber observable type, with each row containing the relationship information per cyber observable.

## Current Workaround

create a file and configuration/mapper for each type of cyber observable

I attached an example file to show what I would like to ingest. I would like to define a relationship between the domain and threat actor, between the domain and campaign, between the  ip and threat actor, and between the ip and campaign. All of these should use the dates in column F and G for each relationship.
[scrubbed.csv](https://github.com/user-attachments/files/15876619/scrubbed.csv)

**Comment by nino-filigran** [comment]
@sweet-mentat we plan to tackle https://github.com/OpenCTI-Platform/opencti/issues/4935 by enabling users to define a conditional value contained in a column that would decide what entity type you have. For example:

| Value/name | entityType |
| --- | --- |
| 111.111.111.111 | IPV4 |
| www.url.com | url |

In the CSV mapper, you will be able to reference column entityType in order to specify which entity you want. Basically, when defining your IPV4 representation, you will be able to say something like " IF column = entityType equal "IPV4" then we will treat your line as an IPV4. Same goes on for all entities. 

As a result, if it's fine with you I'm closing this ticket. Feel free to re-open it if you think it should not be.
