### ISSUE TITLE
[CSV mapper] Missing certain label on import

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7426]
## Description

**In the context of CSV mapper**

When I import entity with labels, if I have several rows with the same entity, but with different labels, they will not all be added.

## Environment

OCTI 6.1.11

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a CSV mapper with two representation : 

![Screenshot 2024-06-19 191358](https://github.com/OpenCTI-Platform/opencti/assets/70956706/2b7959a2-102f-45d9-a930-5d6637e9fb3b)

![Screenshot 2024-06-19 191408](https://github.com/OpenCTI-Platform/opencti/assets/70956706/e166993d-2b8a-454f-9d90-4364f20b4df4)

2. Import this file using this CSV mapper : 

[test_import_label.csv](https://github.com/user-attachments/files/15904092/test_import_label.csv)

-> Look at the created IP, you won't see all the labels on it.

NB: I haven't tested with entities other than IPv4 but I imagine this happens regardless of the entity type.

**Comment by nino-filigran** [comment]
I've tried with another entity type & the end result is the same. 
Interestingly enough, this is the result when you click on "test" when building your mapper: it seems that in the test the 3 labels are detected properly though.

[
  {
    "id": "label--2e034b0a-bcb5-5965-b7a5-0525a767d41d",
    "spec_version": "2.1",
    "type": "label",
    "extensions": {
      "extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba": {
        "extension_type": "new-sdo",
        "type": "Label",
        "converter_csv": "threatActor1,one-label,green"
      }
    },
    "value": "one-label",
    "color": "green"
  },
  {
    "id": "threat-actor--e102a8e0-c665-5f49-8e1c-2f5a921604a5",
    "spec_version": "2.1",
    "type": "threat-actor",
    "extensions": {
      "extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba": {
        "extension_type": "property-extension",
        "type": "Threat-Actor-Group",
        "labels_ids": [
          null
        ],
        "converter_csv": "threatActor1,one-label,green"
      }
    },
    "labels": [
      "one-label"
    ],
    "name": "threatActor1"
  },
  {
    "id": "label--e317f87f-691e-51fe-8a14-066182e5793f",
    "spec_version": "2.1",
    "type": "label",
    "extensions": {
      "extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba": {
        "extension_type": "new-sdo",
        "type": "Label",
        "converter_csv": "threatActor1,two-label,blue"
      }
    },
    "value": "two-label",
    "color": "blue"
  },
  {
    "id": "label--4dd8f5bb-b7a9-5c7b-bd9a-0ee6161dcbee",
    "spec_version": "2.1",
    "type": "label",
    "extensions": {
      "extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba": {
        "extension_type": "new-sdo",
        "type": "Label",
        "converter_csv": "threatActor1,three-label,red"
      }
    },
    "value": "three-label",
    "color": "red"
  }
]

**Comment by Jipegien** [comment]
what is the status of this bug? Why is it in Pause @CelineSebe ?

**Comment by CelineSebe** [comment]
> what is the status of this bug? Why is it in Pause [@CelineSebe](https://github.com/CelineSebe) ?

The bug status is "brainstorm", the source of the issue has not been found. I'm getting back on it.
@Goumies Did you take a look at it finally?

**Comment by labo-flg** [comment]
We have the very same IP addresses used in every line of the CSV.
To my knowledge, this case is not handled by the CSV parser.

The parser will treat the first line, create the new ip and the first label, then move on to the next line.
Next line, same IP => already in bundle so not created again. New label => created.
The algorithm won't add the label to the already created IP object.

This is the same for other attributes made from other representatives in the mapper, such as markings, 
This CSV won't work:

```csv
12.135.55.34,PAP,PAP:GREEN,1
12.135.55.34,TLP,TLP:GREEN,1
```
Only the first PAP marking will be set.

However, this CSV will  work:
```
12.135.55.34,PAP,PAP:GREEN,1,TLP,TLP:GREEN,1
```
Providing a mapper with 2 marking representatives.
![image](https://github.com/user-attachments/assets/819361df-04d6-485b-b4af-b778491e3c3b)
![image](https://github.com/user-attachments/assets/1a5a8001-290d-4776-9008-c6261330eb0f)
![image](https://github.com/user-attachments/assets/69915297-dd46-402e-8bf5-d5c9120e8768)

This issue is also happening actually for any multiple attributes (list).
For instance, parsing attack patterns with `platforms` attribute ;

This CSV won't work:
```
atk1,windows
atk1,linux
```
The bundle created will only have entity `atk1` with `platforms = ["windows"]`.
For the second line, atk1 was already created and is skipped.

This CSV will work (providing list separator `+` in the mapper config for the platforms attribute)
```
atk1,windows+linux
```

I reckon that in the case of multiple representatives (label, marking cases for instance) it can be complicated to produce a working CSV (if you have max 15 labels on your entities, it means 15 label representatives in the mapper, which is 30 new columns in your CSV (some empty if one of your entity has less than 15 labels).

Now to the solution...

The parser code is quite complex, and we would need significant work to 1) understand what's going on, and 2) find a solution (probably not trivial) to add this new behavior to the CSV parser  = being able to handle multiple line with same entity - somehow  merging data from these lines.
Merging raises even more questions... What about multiple lines having same entity but different values for a single attribute ? like an indicator score ?

Significant effort have been already invested just in bug analysis, should we invest a lot more ? (This could be considered a whole new feature actually).

cc @nino-filigran @Jipegien

**Comment by nino-filigran** [comment]
Closing this bug and mark it as won't fix for now, since it would be tackled through the following feature: https://github.com/OpenCTI-Platform/opencti/issues/7400

**Comment by Lhorus6** [comment]
@nino-filigran Do you have a specific issue to follow in which this need will be shipped? To allow the customer to follow it

**Comment by nino-filigran** [comment]
The issue will be higlighted in the above mentioned one when we'll have a fully stable defined approach :)
