### ISSUE TITLE
Can't see reports crowdstrike connector

### ISSUE THREAD

**Issue by symsal** [LuatixHQ/opencti#7653]
## Description

I can't see crowdstrike reports in a main reports page. I just see the report on dashboard inside the widget "Lastest reports". 
Do you know why?

## Environment

opencti standalone (latest)

**Comment by symsal** [comment]
any suggestions?

**Comment by nino-filigran** [comment]
@symsal sorry I did not see your question earlier. 
So if I understand, your issue is that on the welcome page (openCTI/dashboard), in the dashboard view (attached below) you see some Reports with **Author = Crowdstrike** but when you navigate to reports, an filter on Report, with **author = Crowdstrike** you do not find any reports, am I right?

Can I ask you to: 
- provide me the version you're one 
- tell me which filter you use to find (or not) the Crowdstrike reports
- which connector do you use to import Crowdstrike reports? & Who's the user associated with your connector?

**Comment by Jipegien** [comment]
Do not hesitate to reopen the issue if the problem persists.
