### ISSUE TITLE
[Trigger filters] Modify the status of reports after validation of a worbench

### ISSUE THREAD

**Issue by NiQuintin** [LuatixHQ/opencti#7703]
## Description

When a trigger filter is defined on the ImportExternalRefence connector, this will cause a manipulation when validating a workbench on a report, and reset the workflow status to the initial state (New, for example).

## Environment

OpenCTI 6.2.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. From a report created by a feed (e.g. [F] RSS Feed), set a different status from the initial one,
2. Add a filter trigger ([F] RSS Feed) to the ImportExternalRefences connector,
3. A workbench is created, validate it,
4. This will reset the status to "XXXXX adds itself in Creators - Andorra in Contains | replaces NEW in Workflow status".

## Expected Output

The validation of the workbench generated by the trigger shouldn't modify the status on the container
## Actual Output

The status is reset on the initial workflow's step

## Additional information

Here an example 
https://testing.octi.staging.filigran.io/dashboard/analyses/reports/51dbdc70-15bf-4bf6-82d5-f68d96ab0e46/files
https://testing.octi.staging.filigran.io/dashboard/data/ingestion/connectors/c0n3ct0r-f1l1-gr4n-00io-000000000037

**Comment by lndrtrbn** [comment]
**Solution to implement to fix the issue (discussed with @SamuelHassine)**

If I am in a workbench linked to an entity, when I submit the validation of the workbench:
- the modal is asking me if I want to replace the current entity with its last values (because potentially some values have been changed between the time the workbench has been created and now):
  - if I say yes (default), replace all values of the entity with the ones in DB at this moment. Except for the `object refs` if I am in a container,
  - if I say no, keep the data we already have in the bundle.
 
If it is a workbench from data/import, I don't have this choice and current behavior is kept.
