### ISSUE TITLE
Can't remove user in RSS Ingester creation form

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7748]
## Description
Can't remove user from user field in RSS ingester creation form when 

## Reproducible Steps
- Open the RSS Ingester creation form
- Enter a user
- You can't remove the user

![image](https://github.com/user-attachments/assets/6a40d783-a2d5-4722-ba1c-c9844ac9e4cd)

**Comment by romain-filigran** [comment]
After internal discussion, in future we prefer to force the end user to use a dedicated account responsible for ingesting data (taxii, csv, rss) instead of using the System account. 
The idea is to force this information to be filled in a future version, so it doesn't make sense to allow it to be removed now.
