### ISSUE TITLE
CISA KEV flag is inverted (FALSE instead of TRUE)

### ISSUE THREAD

**Issue by damians-filigran** [LuatixHQ/opencti#7978]
## Description

When a vulnerability is on the CISA KEY list, the "CISA KEV" param is inverted

## Environment

1. Linux
2. 6.2.11
3. Web Mac
4. On Filigran SaaS

## Reproducible Steps

1. Set up CISA KEV connector
2. Import CISA KEV list
3. Filter vulnerability list on "CISA KEV = TRUE". All the CISA KEV vulnerabilities are hidden.
4. Filter vulnerability list on "CISA KEV = FALSE". Only the CISA KEV vulnerabilities are shown
4. 
<img width="1421" alt="image" src="https://github.com/user-attachments/assets/4571599b-d0b2-42f4-8204-f374d55f4b2c">

**Comment by romain-filigran** [comment]
The current CISA KEV connector doesn't update the newly added field "CISA KEV". Planned for version 6.3.0

**Comment by nino-filigran** [comment]
@damians-filigran do you still have the issue?

**Comment by nino-filigran** [comment]
@romain-filigran closing this bug since there's no movment on the ticket. This problem will be solved by itself if  I understood well when vulnerabilities will have the field KEV populated. Right now, this behavior exist since for these vulnerabiltities, the value is basically unknown. Feel free to re-open if you disagree or would like to implement a fix.
