### ISSUE TITLE
Import CSV 

### ISSUE THREAD

**Issue by ThreatCTI** [LuatixHQ/opencti#8105]
Why isn't the progress bar showing up?? I created a CSV mapper and applied it to a small sample for import, and it was successfully imported. However, when I tried to import the full sample, it shows null. Is there a maximum limit for import, or should I wait? If I need to wait, why can't I estimate the time, or why doesn't the progress bar appear so that I can know how long it will take, etc...?
![Screenshot from 2024-08-19 09-59-27](https://github.com/user-attachments/assets/7ddd63f1-d7e4-4cde-9427-201df79c14a8)
![Screenshot from 2024-08-19 09-59-34](https://github.com/user-attachments/assets/290e58d5-e620-4da0-8fa3-57a61a681326)
![Screenshot from 2024-08-19 09-59-49](https://github.com/user-attachments/assets/53caa2c2-13a7-4500-8531-b0d4d17baeb6)
![Screenshot from 2024-08-19 10-00-01](https://github.com/user-attachments/assets/82207248-56cb-4447-a84f-ed2d4cde1495)
![Screenshot from 2024-08-19 10-00-13](https://github.com/user-attachments/assets/6da62372-a7ac-4f1c-b4f2-9a793ed23e35)
![Screenshot from 2024-08-19 10-00-56](https://github.com/user-attachments/assets/e3018e98-18d1-4e4c-9061-2361165507fe)
![Screenshot from 2024-08-19 10-01-52](https://github.com/user-attachments/assets/cf38b09e-e1eb-4afc-a0e7-898d5e61a613)

**Comment by ThreatCTI** [comment]
Also, I can't add labels and kill chains because they require entering color, order, etc., and I don't have this data in my sample. Why can't I create default values? For example, in labels, if you don't have a value, a random color can be added, and for kill chains, you can create default values. I hope you can add these features in the next update.
![Screenshot from 2024-08-19 16-32-48](https://github.com/user-attachments/assets/e043aadb-16c3-48d2-96fc-3a2be36708d1)
![Screenshot from 2024-08-19 16-34-04](https://github.com/user-attachments/assets/797500ed-b053-4d66-bea9-93b34908a2d4)

**Comment by nino-filigran** [comment]
@ThreatCTI thanks for your ticket. I'll try to take it point by point. Please let me know your thoughts.

> Why isn't the progress bar showing up?? I created a CSV mapper and applied it to a small sample for import, and it was successfully imported. However, when I tried to import the full sample, it shows null. Is there a maximum limit for import, or should I wait? If I need to wait, why can't I estimate the time, or why doesn't the progress bar appear so that I can know how long it will take, etc...?

In the first set of screens you show, it's about building your mapper, so having a progress bar in these screens do not make sense. 
Then, when you import your CSV, you have this progress bar, showing that your request is being processed by the connector. Once done, then at first, it shows null/X which is an issue we're aware of https://github.com/OpenCTI-Platform/opencti/issues/7992. The waiting time depends on your setup basically and is not something that we can easily calculate. 
![image](https://github.com/user-attachments/assets/412be759-b71c-4a46-9596-2da8dc319111)


> Also, I can't add labels and kill chains because they require entering color, order, etc., and I don't have this data in my sample. Why can't I create default values? For example, in labels, if you don't have a value, a random color can be added, and for kill chains, you can create default values. I hope you can add these features in the next update.

We're aware that representation (like labels) are not working well. In the next releases, we plan to work on them to ensure we can at least define either default values for colors, or ensure that we can in essence, provide labels (and other representations) easily without having to provide a color because this does not make sense. The ticket to follow is this one: it will be updated with the exact approach we will take: https://github.com/OpenCTI-Platform/opencti/issues/7400

Regarding your last point, similarly, being able to define default values for any fields is also something we consider. Please follow the above mentioned ticket

**Comment by nino-filigran** [comment]
Closing your ticket (be aware I've created a specific issue that I've added in the list within the EPIC ticket: https://github.com/OpenCTI-Platform/opencti/issues/8128  )
