### ISSUE TITLE
Messages in push_sync queue unexpectedly truncated

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#8145]
## Description

Seeing lots of hung messages in the push_sync queue that are ending up truncated if they are close to 1mb

When these pile up this queue stalls, Seems like this may be causing a infinite retry loop @richard-julien 

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 6.2.6
3. OpenCTI client: Frontend?
4. Other environment details: Clustered k8s deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Unknown at this time - Seeing it on multiple data sources (TAXII, MISP, custom)

## Additional information

Can provide more logs if needed

Example of the message truncation in the queue (made short for this example)

```json
{
    "type": "bundle",
    "applicant_id": "b0b49ba2-1d61-43ce-9d94-9a0d44cf71cb",
    "content": "eyJ0eXBlIjoiYnVuZGxlIiwiaWQiOiJidW5kbGUtLTdhMjQwYTkyLTYwOWItMTFlZi04MGE0LTAwNTA1NmI1Yjc3OSIsIm9iamVjdHMiOlt7InR5cGUiOiJyZWxhdGlvbnNoaXAiLCJzcGVjX3ZlcnNpb24iOiIyLjEiLCJpZCI6InJlbGF0aW9uc2hpcC0tODE3YmU3MDYtNjA5Yi0xMWVmLThh
   
 ```

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/e6e77eca-9b30-4ff5-8724-c27d7b92f4c8)

Example of a real message
![image](https://github.com/user-attachments/assets/4e4a1a1e-021c-43f4-ae02-281a6a20d8c6)

**Comment by richard-julien** [comment]
Hi @MaxwellDPS , for what I know its the rabbitmq interface that truncate the message when you ask for a visualization.
We succeeded to identify that in some case the bundle execution in the worker timeout on rabbitmq because of too many retries.
To prevent this we implements a split a requeue system in the latest minor.
Can you try to upgrade to the latest minor and check if the number of messages in the sync queue is going up and starts to be consumed?
