### ISSUE TITLE
Incorrect percentage in the knowledge view

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8176]
## Description

When I am on a Knowledge tab of an Intrusion set, the percentage is not calculated correctly in the "Distribution of reports" section (it displays the value of the number of reports as a percentage).

This is probably the case everywhere, not just for Intrusion sets.

## Environment

OCTI 6.2.14

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on an Intrusion set
2. Go on the Knowledge tab
3. Check the percentage (the entity must be contained in at least 1 report)

![image](https://github.com/user-attachments/assets/b9a8ffb0-d2d3-4e2f-afa3-c5350e3b1480)

**Comment by frapuks** [comment]
May be alredy solved ? Because, no problem on local & testing => https://testing.octi.staging.filigran.io/dashboard/threats/intrusion_sets/f274979f-9b63-4f15-8c39-8ae09cc6b547/knowledge/overview?filters=%7B%22mode%22%3A%22and%22%2C%22filters%22%3A%5B%7B%22id%22%3A%2292dcf918-85b2-4553-8696-c13c223f1d09%22%2C%22key%22%3A%22elementWithTargetTypes%22%2C%22values%22%3A%5B%22Attack-Pattern%22%2C%22Malware%22%2C%22Tool%22%2C%22Vulnerability%22%5D%2C%22operator%22%3A%22eq%22%2C%22mode%22%3A%22or%22%7D%5D%2C%22filterGroups%22%3A%5B%5D%7D&searchTerm=&sortBy=created&orderAsc=false

![Image](https://github.com/user-attachments/assets/7e655096-784a-4455-9cb9-809aec917d06)

**Comment by Lhorus6** [comment]
It looks like someone has fixed it, yes
