### ISSUE TITLE
Hamburger buttons to update or delete an attack pattern within an incident doesn't work and redirect to the attack pattern page.

### ISSUE THREAD

**Issue by sancievanneaud** [LuatixHQ/opencti#8330]
## Description

When clicking on the hamburger buttons to update or delete an attack pattern within an incident, the modification drop down menu appears just 2 sec and then redirect to the attack pattern page.

## Environment

2. OpenCTI version: 6.2.18

## Reproducible Steps

1. Go to an incident page
2. Knowledge
3. In Techniques, select Attack Pattern
4. Select Kill chain vue
5. On an attack pattern, click on the hamburger buttons at the right side
6. The modification window appears just 2 sec 
7. The click redirect to the attack pattern page.

## Expected Output

Display the modification drop down menu to click on the update or delete button.

## Actual Output

The modification drop down menu appears just 2 sec and the click redirect to the attack pattern page.

**Comment by romain-filigran** [comment]
Reproduced on any views with kill chain view

**Comment by CelineSebe** [comment]
@nino-filigran @romain-filigran I solved the issue with the redirection, but when I try to update, it's not possible because we have a component, relationshipEditionComponent, which doesn't retrieve the relationship here.
Based on my investigation, what I understand is that the relationship we're trying to open, update, or delete is at play here. But, we might only have access to the entity.

My question is: 
Do we want to update the relationship or the entity in this context?

**Comment by nino-filigran** [comment]
For me, we expect to edit the relation. Because if you're redirected to the attack pattern's page, then you will need to find manually the entity you were in to potentially update or delete the relation, which is annoying. Is that possible @CelineSebe ?

**Comment by CelineSebe** [comment]
> For me, we expect to edit the relation. Because if you're redirected to the attack pattern's page, then you will need to find manually the entity you were in to potentially update or delete the relation, which is annoying. Is that possible @CelineSebe ?

@nino-filigran When you click on the line, you are redirected to the entity that you can modify, delete, etc. With the 3 points of the line (kill chain view), you can completely delete the entity with the previous code, not the relationship.

**Comment by nino-filigran** [comment]
Yes. & the goal is that if you click on the 3 dots, we should access the relationship, not the entity.

**Comment by SouadHadjiat** [comment]
The issue is that we now query and display attack patterns in this screen, and not relationships, since the work done on this PR https://github.com/OpenCTI-Platform/opencti/pull/7492 , more specifically since this commit in the PR https://github.com/OpenCTI-Platform/opencti/pull/7492/commits/5b2806feb0acf8ee15db51884f7a97cc475bc250

why did we change the logic at that time ? and do we want to change it back now ? @nino-filigran

**Comment by nino-filigran** [comment]
Ok I see your point  @SouadHadjiat and I've tested with other entities, within the incident knowledge views. 
The confusion or problem comes from the fact that the attack pattern view is different from other views: 
- in other views, you have either an entity view (when you edit you are rpompted the entity) or a relation (when you click on edit, you're redirected to the relation)
- in attack pattern, you have the matrix, the COA, the list... All of them are representing implicitely the entity. But we don't have this relation view.

This is what created the confusion on the requested fix and it's my bad. 
Therefore, if you're ok the fix should be : 
- to fix the redirection
- if click on update, we update the entity (and not the relation as I was wrong)

ok with this @romain-filigran ?

**Comment by nino-filigran** [comment]
After a discussion: we will remove completly the "three dots" since we are in this view **vizualising** only the **entity** and not the **relation**.
Click on the line will redirect to the entity.

In this new tasks, we will add a new view to be able to view, edit and manage the relation between the entity & the relation: https://github.com/OpenCTI-Platform/opencti/issues/8835
