### ISSUE TITLE
MITRE ATT&CK ordering is not applied in the matrix view

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#8424]
## Description

When displaying the MITRE matrix view, MITRE ATT&CK kill chain phases ordering is not take into account.

![image (4)](https://github.com/user-attachments/assets/d65e782b-fc0c-48ed-9320-9a545035f5dc)

![image (5)](https://github.com/user-attachments/assets/99c7ea48-5c34-47a1-ab15-534724a39fda)

## Environment

OpenCTI version: 6.3.1

**Comment by seanthegeek** [comment]
@romain-filigran @SouadHadjiat @Gwendoline-FAVRE-FELIX I've noticed that once imported, all of the kill chain phases are set to order position `0`. It would be great of the phases had the correct order when they are imported, rather than having to manually edit the order in OpenCTI Taxonomies?  Does STIX not provide kill chain order information?
