### ISSUE TITLE
English grammar errors in the toggle labels for the "Update a group" panel 

### ISSUE THREAD

**Issue by seanthegeek** [LuatixHQ/opencti#8445]
## Description

Three of the toggle options at the bottom of the "Update a group" panel have English grammar errors that make what the option does unclear.

## Environment

1. OS (where OpenCTI server runs): Debain 12
2. OpenCTI version: 6.3.1
3. OpenCTI client: Frontend

## Reproducible Steps

1. Navigate to Settings> Security
2. Click Groups
3. Click on an existing group
4. Click on the edit/pencil button

Label text | Corrected grammar| Notes
------------|----------------------|--------
Automatically authorize this group to new marking definition || I'm not sure what this is, considering managing marking definitions are granted be a role capability 
Do not accumulate creators for the users of this group ||I found [the request](https://github.com/OpenCTI-Platform/opencti/issues/7290) that added the option, but I don't know what accumulating creators means, and I can't find a reference in the documentation 
Deny users to delete content not created by them | Do not allow users to delete content created by other users

## Screenshots (optional)

![image](https://github.com/user-attachments/assets/7cb02ed2-e55e-4bda-9bd3-be0a1d3d8d40)

**Comment by nino-filigran** [comment]
Hi @seanthegeek thanks for your feedback. We'll treat your bug as soon as we can. However I can already give you some hints for your comments in the ticket:

- I'm not sure what this is, considering managing marking definitions are granted be a role capability: sometimes, data is incoming with some specific (and new) marking that are not in your platform. Therefore, these markings automatically needs to be added to the group (which the user belongs to) in order to be able to create the data with the correct marking. It is especially usefull in the context of connectors. This behavior exists on the side than the "manage marking definition" capability since as explained above, this action needs to be done automatically. You still need the capability manage marking definition on the top of it.
- Do not accumulate creators for the users of this group: I'll take a concreate example. When you create a Report for instance, the Author field is always unique in the platform. However as soon as you contribute to the report (ex: update a description), you'll aslo be in the **creator** of the report. Therefore, **creators** can accumulate (having multiple creators in the filed). When you enable this toggle, a user that would edit a field of the given report in our example would be able to perform an update but will not appear in creator. The goal is to keep tracabilité & ownership of data. This is especially useful in the context of the last option **Deny users to delete content not created by them**, because if you manage to ensure that you have a single creator, you can also manage, when enabling this toggle, that only the creator can delete its own data. This way, you can avoid having users that delete your data by mistake! It's an additional protection mechanism on the top of the capability "delete knowledge".

**Comment by seanthegeek** [comment]
I see, so maybe better labels would be

Label text | Corrected text
------------|----------------
Automatically authorize this group to new marking definition | Allow these users to create new marking definitions
Do not accumulate creators for the users of this group | Do not add these users as creators when they edit content
Deny users to delete content not created by them | Do not allow these users to delete content created by other users

**Comment by nino-filigran** [comment]
- Allow these users to create new marking definitions: this is too narrowed. It's only create, but really grant the group new marking definitions, as it's written. 
- Do not add these users as creators when they edit content: in the end, you can also add yourself as a creator, which is slightly bigger than your suggestion. 




As a result, we will only change the last one ( Deny users to delete content not created by them **TO** Do not allow these users to delete content created by other users)
