### ISSUE TITLE
Inability to View Dashboard for All Users

### ISSUE THREAD

**Issue by ThreatCTI** [LuatixHQ/opencti#8457]
I cannot change the dashboard; a message indicates that I do not have permission to do so, as shown in the picture. This is despite the fact that I am an admin and have created the dashboard as well.
![Screenshot 2024-09-23 161900](https://github.com/user-attachments/assets/40345835-12ad-4867-b8b3-192c2e1a2f25)
![Screenshot 2024-09-23 161833](https://github.com/user-attachments/assets/c0715d11-615d-4d37-af28-5943a4d5d26c)

**Comment by nino-filigran** [comment]
@ThreatCTI can you please: 
- let me know what are the capabilities associated to the role of your user? (do you have the edit dashboard one)?
- can you give a me reproducation case? (are you only trying to modify the authorized members)?

I also have an error but I'm not sure I'm doing the same action as you.

**Comment by ThreatCTI** [comment]
Hi @nino-filigran,

Yes, I have the 'edit dashboard' permission as I am the admin and I created the dashboard myself.
The issue occurs when I try to modify the dashboard or add authorized members. I am unable to make any changes despite having all the necessary permissions.
Are there any additional steps or settings I should check to resolve this issue?

**Comment by nino-filigran** [comment]
Ok, so to recap: 

- you have an admin role, which means you have ALL capabilities (including the bypass all capability capability) 
- with you user you create a dashboard
- you click on authorized members (the lock icon)
- you add some user/group or org with an access right "can view"
- you save
- you get the error.

Is this correct?
What version of OpencCTI are you using? 

Can you please verify that you're on 6.3.4? If not could you maybe upgrade to this version? The problem seems not to happen on this version.
