### ISSUE TITLE
Relationship "<Malware> authored by <Threat Actor Individual>" not properly displayed in Knowledge tab

### ISSUE THREAD

**Issue by ups1decyber** [LuatixHQ/opencti#8576]
## Description

I have created a relationship "authored by" between a malware and a threat actor individual. Now, when I open the knowledge tab of the malware, I can see "Threat actors (1)" in the list on the right. However, when I click on "Threat actors", the displayed list is empty.

## Environment

1. OS (where OpenCTI server runs): -
2. OpenCTI version: OpenCTI 6.3.1
3. OpenCTI client: -
4. Other environment details: -

## Reproducible Steps

1. Create a malware, threat actor individual and report.
2. In the report, add the malware and threat actor entities
3. Create a "authored by" relationship for the malware and threat actor entities
4. Open the knowledge tab of the malware **or** open the knowledge tab of the threat actor individual
5. Look at the menu on the right. On the malware page, it should say "Threat Actors (1)", but the corresponding list does not contain any items. On the threat actor individual page, it should say "Malware (1)", but the corresponding list does not contain any items. This is true for both, the "entities view" and the "relationships view".

## Expected Output

I would expect the lists to contain items that describe the "authored by" relationship.

## Actual Output

No list items

## Additional information

-

## Screenshots (optional)

![image](https://github.com/user-attachments/assets/94e23e76-7212-426e-86d0-7d8713f02d50)

**Comment by nino-filigran** [comment]
The problem is generic to Intrusion Sets, Threat Actor individual & Threat Actor group.
The fix is to: 
- for any relation malware -> authored by -> threat actor/intrusion set, display: 
   - in the malware knowledge views, in "all threats view" & in the "intrusion set" view, the threat actors and/or the intrusion set. Also, when switching to relation view, the authored by must be displayed.
   - in the threat actors/intrusion knowledges views, in "malware" view, have the malware. And when switching to relation view, be able to display the authored by.
