### ISSUE TITLE
[RBAC] User kicked out when accessing a forbidden resource

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8748]
## Description

I created a user who can only access a TAXII collection in order to share data. I have a Role containing only one capability: Access Data Sharing (and nothing else).

- He can access the TAXII collection, as desired
- But it can also access the interface. This isn't a problem, because he can't see anything.

However, he can click on the “Data > Data sharing” menu. 

![image](https://github.com/user-attachments/assets/e7659ec2-646d-4434-9e89-eff174409e9e)

When he does this, two problems arise:

1. He sees the page for a quarter of a second, and therefore sees the existing Live streams (which shouldn't be possible).
2. It is thrown out of the platform rather than getting a “you are not authorized to access this screen” error message.

## Environment

OCTI 6.3.6

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a user part of a group with all markings and with a role containing only "Access data sharing"
2. Log on to the platform with this user and try to access the “Data > Data sharing” page.

## Expected Output

No “Data > Data sharing” button at all

OR

Have it but:
- No page preview for a quarter of a second
- Get an error message rather than getting thrown out

NB: Even better would be not to be able to log in to the interface ;)

**Comment by nino-filigran** [comment]
For me the fix is: 
- do not log out user 
- ability to view the menu data sharing
- ability to access any pages within data sharing WITHOUT the ability to manage any feeds, taxii collection.

Ok with this @romain-filigran ?

**Comment by romain-filigran** [comment]
Yes @nino-filigran , it makes sense

**Comment by marieflorescontact** [comment]
Problem occurs when menu is collapsed:
even if the UI says that we are redirected to Data sharing, we are redirected to the url `opencti/dashboard/data/entities /etc`  for wich `Knowledge` capability is required because of the `EntitiesStixDomainObjectsLinesPaginationQuery`, platform crashes:
![Image](https://github.com/user-attachments/assets/acc03ff8-b43c-4470-a46c-1cde39667b55)


If menu is not collapse:
![Image](https://github.com/user-attachments/assets/95936fe8-a331-42f9-9f9e-95f052a32c02)
we are redirected to url `dashboard/data/sharing/streams?` wich is ok with `dataSharing` capability

**Comment by nino-filigran** [comment]
Thanks for investigating @marieflorescontact  👍 
Will we able to fix this?
