### ISSUE TITLE
Attack pattern Title Modification issue

### ISSUE THREAD

**Issue by sudesh0sudesh** [LuatixHQ/opencti#8874]
## Description

Eventhough the name of Attack pattern is set and Alias as pattern ID is set. For some reason when connectors inject killchain with pattern id. It is replacing the pattern Name with ID and Alias with Name.

## Environment

1. OS (where OpenCTI server runs): docker
2. OpenCTI version: 6.3.6
<img width="845" alt="Screenshot 2024-11-01 at 16 19 03" src="https://github.com/user-attachments/assets/72bcad5b-cbde-4c1a-9572-79bca9ae818b">

**Comment by sudesh0sudesh** [comment]
<img width="832" alt="Screenshot 2024-11-01 at 16 30 27" src="https://github.com/user-attachments/assets/6d6d7fac-bcc6-4515-8c20-14d774d3ca1f">

**Comment by nino-filigran** [comment]
@sudesh0sudesh sorry but I'm not sure to follow, can you please provide more details ?
- so at first, you have an attack pattern with a name & its alias as an ID, right?
- alienvault is sending you another attack pattern, & your Alias & name are swapped.

Is that the problem?

**Comment by sudesh0sudesh** [comment]
Yep

**Comment by nino-filigran** [comment]
I don't see the problem from a technical standpoint here: our upsert merchanism is doing its job. For any entity, if the entity A has an alias and a user creates an entity of the same type with the name = alias of entity A, then the entity A name will become it's alias. 
So there's no bug there, unless I misunderstood your issue.

I can however understand that you don't want your entities to change name. In which case at the moment, what I can suggest you is to reduce the confidence level of the specific users ingesting some Attack Patterns (in your case AlienVault), so that these users will stop updating existing entities name. Be careful however, it will also prvent the update of the entity. 
We have a feature to prevent the update of the name/value of an entity: https://github.com/OpenCTI-Platform/opencti/issues/8014

Does my answer your ticket? Or did I misunderstand your issue?

**Comment by sudesh0sudesh** [comment]
Ahh, Got it, will utilise the connector trust. Thanks
