### ISSUE TITLE
Granularity for "create/update knowledge"

### ISSUE THREAD

**Issue by lightw1s3** [LuatixHQ/opencti#8938]
## Use case

With the current roles in the platform a person can edit everything or not edit anything. 
We need to have a role where a user can create or add information to an entity only if the user from another organisation confirms its inclusion. Understanding that underneath this we would need to add an alerting function or ticket management section to do this.
We believe this would be useful as it would provide more granularity to role management. 

## Current solution

Currently OpenCTI does not have a solution for this as the role that can be given to a user is to edit/modify entities but there is no granularity within this role. It is possible to apply a trust level to the user but this would only control the non-modification of objects with a higher trust level than the one given to the user. 
There is no such thing as a ‘test analyst’ role where the user can be given the option to add or modify information under the supervision of another role.

## Proposed solution

It is proposed to implement a role linked to another parent role. Where every action performed by a group with such a role associated must be approved by a user of another group created.

And, thank you very much for your work in advance.

## If the feature request is approved, would you be willing to submit a PR?

No.

**Comment by nino-filigran** [comment]
Hi @lightw1s3 we're working on a new functionality called draft that will replace the workbench. You will be able to start a draft manually. With draft, we plan a new feature to request a peer validation, in order to have the changes ingested. I guess this will solve your use case. As a reuslt, I'm closing this feature request, as it's a duplicate. Feel free to follow this ticket resolution: https://github.com/OpenCTI-Platform/opencti/issues/8707
