### ISSUE TITLE
When uploading or creating a file in Content tab (Report for example) an error occurs

### ISSUE THREAD

**Issue by lndrtrbn** [LuatixHQ/opencti#9149]
## Description

When uploading or creating a file in Content tab (Report for example) an error `Update indexing fail` occurs.
It does not occur every time so be sure to try multiple times.

Still the file seems to be uploaded.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to a Report and then Content tab,
2. Create a new file and validate,
3. An error `Update indexing fail` appears, the form stays disabled and the modal won't close.
4. The file seems still uploaded.

> If you didn't have the error, retry.

## Expected Output

Works every time.

## Actual Output

Sometimes error appears.

**Comment by JeremyCloarec** [comment]
This can always be reproduced when adding files with file markings

**Comment by JeremyCloarec** [comment]
After further analysis: the error comes from the introduction of file_markings on x_opencti_files after this PR https://github.com/OpenCTI-Platform/opencti/pull/9017
Since these file_markings are resolved in loadElementsWithDependencies, we are trying to send these resolved files to elastic when updating the element in stixCoreObjectPush, causing an indexing failure
